
from app.db.models.user import User
from app.db.models.statutaffectation import StatutAffectation
from app.db.models.statuteleve import StatutEleve
from app.db.models.genre import Genre
from app.db.models.domaine_resao import DomaineResao
from app.db.models.discipline import Discipline
from app.db.models.specialite import Specialite
from app.db.models.diplome import Diplome
from app.db.models.nature_piece_identite import NaturePieceidentite
from app.db.models.statut import Statut
from app.db.models.classe_situation_administrative import ClasseSituationAdministrative
from app.db.models.type_emploi import TypeEmploi
from app.db.models.typeinformationcontact import TypeInformationContact
from app.db.models.informationcontact import InformationContact
from app.db.models.nationalite import Nationalite
from app.db.models.nature_acte_nomination_dans_emploi import NatureActeNominationDansEmploi
from app.db.models.emploi import Emploi
from app.db.models.categorie_actualite import CategorieActualite
from app.db.models.actualite import Actualite
from app.db.models.communique import Communique
from app.db.models.statut_service import StatutService
from app.db.models.categorie_phototheque import CategoriePhototheque
from app.db.models.phototheque import Phototheque
from app.db.models.statut_situation_administrative import StatutSituationAdministrative
from app.db.models.echelon import Echelon
from app.db.models.groupe_emploi import GroupeEmploi
from app.db.models.categorie import Categorie
from app.db.models.grade import Grade
from app.db.models.fonction import Fonction
from app.db.models.type_agent import TypeAgent
from app.db.models.type_message import TypeMessage
from app.db.models.statut_message import StatutMessage
from app.db.models.message import Message
from app.db.models.validation_fiche import ValidationFiche
from app.db.models.statut_agent import StatutAgente
from app.db.models.pays import Pays
from app.db.models.ville import Ville
from app.db.models.situation_matrimoniale import SituationMatrimoniale
from app.db.models.fonction_actuelle import FonctionActuelle
from app.db.models.fiche_validation import FicheValidation
from app.db.models.typedocumentjustificatif import TypeDocumentJustificatif
from app.db.models.nature_acte_nomination_fonctionactuelle import NatureActeNominationFonctionactuelle
from app.db.models.typedocumentjustificatif import TypeDocumentJustificatif
from app.db.models.documentjustificatif import DocumentJustificatif
from app.db.models.positionmilitaire import PositionMilitaire
from app.db.models.role import Role

from app.db.models.type_structure import TypeStructure
from app.db.models.structure import Structure
from app.db.models.service import Service
from app.db.models.groupe import Groupe
from app.db.models.parcours import Parcours
from app.db.models.niveau import Niveau
from app.db.models.promotion import Promotion
from app.db.models.faculte import Factulte
from app.db.models.departement import Departement
from app.db.models.filiere import Filiere
from app.db.models.position_administrative import PositionAdministrative
from app.db.models.auth_session import AuthSession
from app.db.models.login_attempt_state import LoginAttemptState
from app.db.models.password_reset_token import PasswordResetToken
from app.db.models.permission import Permission
from app.db.models.user_permission import UserPermission
from app.db.models.type_recrutement import TypeRecrutement
from app.db.models.eleve import Eleve
from app.db.models.conjoint import Conjoint
from app.db.models.situation_administrative import SituationAdministrative 
from app.db.models.agent import Agent

