"""update niveau naturepieceidentites 2

Revision ID: 032c3861fea0
Revises: 0538a13a59f8
Create Date: 2026-08-18 15:10:14.070878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '032c3861fea0'
down_revision: Union[str, Sequence[str], None] = '0538a13a59f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
