"""update BD des tables 

Revision ID: 0532ac85d189
Revises: b40ce523e4be
Create Date: 2026-08-19 12:31:23.229884

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0532ac85d189'
down_revision: Union[str, Sequence[str], None] = 'b40ce523e4be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validation_fiches',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_mode', sa.Boolean(), nullable=True),
    sa.Column('supprime_le', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('situation_administratives',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('numero_acte_nomination_dans_emploi', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('date_signature_acte_nomination_dans_emploi', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_premiere_prise_service_fonction_publique', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_premiere_prise_service_structure', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_depart_retraite', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_radiation', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_depart_mouvement', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_retour_mouvement', sa.DateTime(timezone=True), nullable=True),
    sa.Column('adresse_bureau', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('adresse_personnelle', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('telephone_bureau', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('telephone_domicile', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('numero_telephone_1', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('numero_telephone_2', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('email_institutionnel', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('email_personnel', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('designation_poste', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('numero_acte_nomination_fonctionactuelle', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('date_signature_acte_nomination_fonctionactuelle', sa.DateTime(timezone=True), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_mode', sa.Boolean(), nullable=True),
    sa.Column('supprime_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_equivqlence', sa.Boolean(), nullable=False),
    sa.Column('statut_situation_administrative_uid', sa.Uuid(), nullable=True),
    sa.Column('emploi_uid', sa.Uuid(), nullable=True),
    sa.Column('classe_situation_administrative_uid', sa.Uuid(), nullable=True),
    sa.Column('echelon_uid', sa.Uuid(), nullable=True),
    sa.Column('nature_acte_nomination_dans_emploi_uid', sa.Uuid(), nullable=True),
    sa.Column('nature_acte_nomination_dans_fonctionactuelle_uid', sa.Uuid(), nullable=True),
    sa.Column('diplome_uid', sa.Uuid(), nullable=True),
    sa.Column('position_administrative_uid', sa.Uuid(), nullable=True),
    sa.Column('position_militaire_uid', sa.Uuid(), nullable=True),
    sa.Column('fonction_actuelle_uid', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['classe_situation_administrative_uid'], ['emplois.uid'], ),
    sa.ForeignKeyConstraint(['diplome_uid'], ['diplomes.uid'], ),
    sa.ForeignKeyConstraint(['echelon_uid'], ['echelons.uid'], ),
    sa.ForeignKeyConstraint(['emploi_uid'], ['emplois.uid'], ),
    sa.ForeignKeyConstraint(['fonction_actuelle_uid'], ['fonction_actuelles.uid'], ),
    sa.ForeignKeyConstraint(['nature_acte_nomination_dans_emploi_uid'], ['nature_acte_nomination_dans_emplois.uid'], ),
    sa.ForeignKeyConstraint(['nature_acte_nomination_dans_fonctionactuelle_uid'], ['nature_acte_nomination_fonctionactuelles.uid'], ),
    sa.ForeignKeyConstraint(['position_administrative_uid'], ['position_administratives.uid'], ),
    sa.ForeignKeyConstraint(['position_militaire_uid'], ['position_militaires.uid'], ),
    sa.ForeignKeyConstraint(['statut_situation_administrative_uid'], ['statut_situation_administratives.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_situation_administratives_classe_situation_administrative_uid'), 'situation_administratives', ['classe_situation_administrative_uid'], unique=False)
    op.create_index(op.f('ix_situation_administratives_diplome_uid'), 'situation_administratives', ['diplome_uid'], unique=False)
    op.create_index(op.f('ix_situation_administratives_echelon_uid'), 'situation_administratives', ['echelon_uid'], unique=False)
    op.create_index(op.f('ix_situation_administratives_emploi_uid'), 'situation_administratives', ['emploi_uid'], unique=False)
    op.create_index(op.f('ix_situation_administratives_fonction_actuelle_uid'), 'situation_administratives', ['fonction_actuelle_uid'], unique=False)
    op.create_index(op.f('ix_situation_administratives_nature_acte_nomination_dans_emploi_uid'), 'situation_administratives', ['nature_acte_nomination_dans_emploi_uid'], unique=False)
    op.create_index(op.f('ix_situation_administratives_nature_acte_nomination_dans_fonctionactuelle_uid'), 'situation_administratives', ['nature_acte_nomination_dans_fonctionactuelle_uid'], unique=False)
    op.create_index(op.f('ix_situation_administratives_position_administrative_uid'), 'situation_administratives', ['position_administrative_uid'], unique=False)
    op.create_index(op.f('ix_situation_administratives_position_militaire_uid'), 'situation_administratives', ['position_militaire_uid'], unique=False)
    op.create_index(op.f('ix_situation_administratives_statut_situation_administrative_uid'), 'situation_administratives', ['statut_situation_administrative_uid'], unique=False)
    op.add_column('enseignants', sa.Column('conjoint_uid', sa.Uuid(), nullable=True))
    op.add_column('enseignants', sa.Column('situation_matrimoniale_uid', sa.Uuid(), nullable=True))
    op.add_column('enseignants', sa.Column('situation_administrative_uid', sa.Uuid(), nullable=True))
    op.add_column('enseignants', sa.Column('validation_fiche_uid', sa.Uuid(), nullable=True))
    op.drop_index(op.f('ix_enseignants_diplome_uid'), table_name='enseignants')
    op.create_index(op.f('ix_enseignants_conjoint_uid'), 'enseignants', ['conjoint_uid'], unique=False)
    op.create_index(op.f('ix_enseignants_situation_administrative_uid'), 'enseignants', ['situation_administrative_uid'], unique=False)
    op.create_index(op.f('ix_enseignants_situation_matrimoniale_uid'), 'enseignants', ['situation_matrimoniale_uid'], unique=False)
    op.create_index(op.f('ix_enseignants_validation_fiche_uid'), 'enseignants', ['validation_fiche_uid'], unique=False)
    op.drop_constraint(op.f('enseignants_diplome_uid_fkey'), 'enseignants', type_='foreignkey')
    op.create_foreign_key(None, 'enseignants', 'situation_administratives', ['situation_administrative_uid'], ['uid'])
    op.create_foreign_key(None, 'enseignants', 'validation_fiches', ['validation_fiche_uid'], ['uid'])
    op.create_foreign_key(None, 'enseignants', 'conjoints', ['conjoint_uid'], ['uid'])
    op.create_foreign_key(None, 'enseignants', 'situation_matrimoniales', ['situation_matrimoniale_uid'], ['uid'])
    op.drop_column('enseignants', 'diplome_uid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enseignants', sa.Column('diplome_uid', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'enseignants', type_='foreignkey')
    op.drop_constraint(None, 'enseignants', type_='foreignkey')
    op.drop_constraint(None, 'enseignants', type_='foreignkey')
    op.drop_constraint(None, 'enseignants', type_='foreignkey')
    op.create_foreign_key(op.f('enseignants_diplome_uid_fkey'), 'enseignants', 'diplomes', ['diplome_uid'], ['uid'])
    op.drop_index(op.f('ix_enseignants_validation_fiche_uid'), table_name='enseignants')
    op.drop_index(op.f('ix_enseignants_situation_matrimoniale_uid'), table_name='enseignants')
    op.drop_index(op.f('ix_enseignants_situation_administrative_uid'), table_name='enseignants')
    op.drop_index(op.f('ix_enseignants_conjoint_uid'), table_name='enseignants')
    op.create_index(op.f('ix_enseignants_diplome_uid'), 'enseignants', ['diplome_uid'], unique=False)
    op.drop_column('enseignants', 'validation_fiche_uid')
    op.drop_column('enseignants', 'situation_administrative_uid')
    op.drop_column('enseignants', 'situation_matrimoniale_uid')
    op.drop_column('enseignants', 'conjoint_uid')
    op.drop_index(op.f('ix_situation_administratives_statut_situation_administrative_uid'), table_name='situation_administratives')
    op.drop_index(op.f('ix_situation_administratives_position_militaire_uid'), table_name='situation_administratives')
    op.drop_index(op.f('ix_situation_administratives_position_administrative_uid'), table_name='situation_administratives')
    op.drop_index(op.f('ix_situation_administratives_nature_acte_nomination_dans_fonctionactuelle_uid'), table_name='situation_administratives')
    op.drop_index(op.f('ix_situation_administratives_nature_acte_nomination_dans_emploi_uid'), table_name='situation_administratives')
    op.drop_index(op.f('ix_situation_administratives_fonction_actuelle_uid'), table_name='situation_administratives')
    op.drop_index(op.f('ix_situation_administratives_emploi_uid'), table_name='situation_administratives')
    op.drop_index(op.f('ix_situation_administratives_echelon_uid'), table_name='situation_administratives')
    op.drop_index(op.f('ix_situation_administratives_diplome_uid'), table_name='situation_administratives')
    op.drop_index(op.f('ix_situation_administratives_classe_situation_administrative_uid'), table_name='situation_administratives')
    op.drop_table('situation_administratives')
    op.drop_table('validation_fiches')
    # ### end Alembic commands ###
