"""update niveau naturepieceidentites

Revision ID: 0538a13a59f8
Revises: ec09ed89b33d
Create Date: 2026-08-18 15:08:34.846084

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0538a13a59f8'
down_revision: Union[str, Sequence[str], None] = 'ec09ed89b33d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_niveaux_cree_par'), table_name='niveaux')
    op.drop_index(op.f('ix_niveaux_modifie_par'), table_name='niveaux')
    op.drop_index(op.f('ix_niveaux_supprime_par'), table_name='niveaux')
    op.drop_constraint(op.f('niveaux_supprime_par_fkey'), 'niveaux', type_='foreignkey')
    op.drop_constraint(op.f('niveaux_cree_par_fkey'), 'niveaux', type_='foreignkey')
    op.drop_constraint(op.f('niveaux_modifie_par_fkey'), 'niveaux', type_='foreignkey')
    op.drop_column('niveaux', 'supprime_par')
    op.drop_column('niveaux', 'cree_par')
    op.drop_column('niveaux', 'modifie_par')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('niveaux', sa.Column('modifie_par', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('niveaux', sa.Column('cree_par', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('niveaux', sa.Column('supprime_par', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('niveaux_modifie_par_fkey'), 'niveaux', 'users', ['modifie_par'], ['uid'])
    op.create_foreign_key(op.f('niveaux_cree_par_fkey'), 'niveaux', 'users', ['cree_par'], ['uid'])
    op.create_foreign_key(op.f('niveaux_supprime_par_fkey'), 'niveaux', 'users', ['supprime_par'], ['uid'])
    op.create_index(op.f('ix_niveaux_supprime_par'), 'niveaux', ['supprime_par'], unique=False)
    op.create_index(op.f('ix_niveaux_modifie_par'), 'niveaux', ['modifie_par'], unique=False)
    op.create_index(op.f('ix_niveaux_cree_par'), 'niveaux', ['cree_par'], unique=False)
    # ### end Alembic commands ###
