"""update Communique fields nombre_vues

Revision ID: 1f8e330e808b
Revises: ec581b0be72d
Create Date: 2026-09-02 10:32:01.227047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f8e330e808b'
down_revision: Union[str, Sequence[str], None] = 'ec581b0be72d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('communiques', 'nombre_vues',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_communiques_nombre_vues'), 'communiques', ['nombre_vues'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_communiques_nombre_vues'), table_name='communiques')
    op.alter_column('communiques', 'nombre_vues',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
