"""add structure deschamps update 

Revision ID: 378f15a0565c
Revises: 612f0eb1173c
Create Date: 2026-08-22 08:27:09.082017

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '378f15a0565c'
down_revision: Union[str, Sequence[str], None] = '612f0eb1173c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('structures', 'code',
               existing_type=sa.VARCHAR(length=255),
               type_=sqlmodel.sql.sqltypes.AutoString(length=50),
               existing_nullable=True)
    op.create_unique_constraint(None, 'structures', ['libelle'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'structures', type_='unique')
    op.alter_column('structures', 'code',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=50),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
