"""ajout des tables 

Revision ID: 37cd784f200f
Revises: c2087dac9ec3
Create Date: 2026-08-18 19:59:13.667625

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37cd784f200f'
down_revision: Union[str, Sequence[str], None] = 'c2087dac9ec3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fonction_actuelles',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cree_par', sa.Uuid(), nullable=True),
    sa.Column('modifie_par', sa.Uuid(), nullable=True),
    sa.Column('supprime_par', sa.Uuid(), nullable=True),
    sa.Column('is_mode', sa.Boolean(), nullable=True),
    sa.Column('supprime_le', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cree_par'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['modifie_par'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['supprime_par'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_fonction_actuelles_cree_par'), 'fonction_actuelles', ['cree_par'], unique=False)
    op.create_index(op.f('ix_fonction_actuelles_modifie_par'), 'fonction_actuelles', ['modifie_par'], unique=False)
    op.create_index(op.f('ix_fonction_actuelles_supprime_par'), 'fonction_actuelles', ['supprime_par'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fonction_actuelles_supprime_par'), table_name='fonction_actuelles')
    op.drop_index(op.f('ix_fonction_actuelles_modifie_par'), table_name='fonction_actuelles')
    op.drop_index(op.f('ix_fonction_actuelles_cree_par'), table_name='fonction_actuelles')
    op.drop_table('fonction_actuelles')
    # ### end Alembic commands ###
