"""update Agent table 

Revision ID: 39e78e0b0173
Revises: 0532ac85d189
Create Date: 2026-08-19 12:39:54.124836

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39e78e0b0173'
down_revision: Union[str, Sequence[str], None] = '0532ac85d189'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('prenoms', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('matricule', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('date_naissance', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lieu_naissance', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('telephone_principal', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('telephone_secondaire', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('email_professionnel', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('email_personneö', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('quartier', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('nom_jeune_fille', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('lieu_habitation', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('date_recrutement', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_depart', sa.DateTime(timezone=True), nullable=True),
    sa.Column('nombre_enfant', sa.Integer(), nullable=False),
    sa.Column('nom_prenoms_pere', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('nom_prenoms_mere', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('numero_piece_identite', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cree_par_uid', sa.Uuid(), nullable=True),
    sa.Column('conjoint_uid', sa.Uuid(), nullable=True),
    sa.Column('modifie_par_uid', sa.Uuid(), nullable=True),
    sa.Column('supprime_par_uid', sa.Uuid(), nullable=True),
    sa.Column('etat_handicap', sa.Boolean(), nullable=True),
    sa.Column('is_mode', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('supprime_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_premiere_prise_service_dans_structure', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_premiere_prise_service_fonction_publique', sa.DateTime(timezone=True), nullable=True),
    sa.Column('nature_piece_identite_uid', sa.Uuid(), nullable=True),
    sa.Column('genre_uid', sa.Uuid(), nullable=True),
    sa.Column('type_agent_uid', sa.Uuid(), nullable=True),
    sa.Column('fonction_uid', sa.Uuid(), nullable=True),
    sa.Column('user_uid', sa.Uuid(), nullable=True),
    sa.Column('nationalite_uid', sa.Uuid(), nullable=True),
    sa.Column('type_recrutement_uid', sa.Uuid(), nullable=True),
    sa.Column('structure_uid', sa.Uuid(), nullable=True),
    sa.Column('situation_matrimoniale_uid', sa.Uuid(), nullable=True),
    sa.Column('specialite_uid', sa.Uuid(), nullable=True),
    sa.Column('situation_administrative_uid', sa.Uuid(), nullable=True),
    sa.Column('emploi_uid', sa.Uuid(), nullable=True),
    sa.Column('grade_uid', sa.Uuid(), nullable=True),
    sa.Column('statut_uid', sa.Uuid(), nullable=True),
    sa.Column('validation_fiche_uid', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['conjoint_uid'], ['conjoints.uid'], ),
    sa.ForeignKeyConstraint(['cree_par_uid'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['emploi_uid'], ['emplois.uid'], ),
    sa.ForeignKeyConstraint(['fonction_uid'], ['fonctions.uid'], ),
    sa.ForeignKeyConstraint(['genre_uid'], ['genres.uid'], ),
    sa.ForeignKeyConstraint(['grade_uid'], ['grades.uid'], ),
    sa.ForeignKeyConstraint(['modifie_par_uid'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['nationalite_uid'], ['nationalites.uid'], ),
    sa.ForeignKeyConstraint(['nature_piece_identite_uid'], ['nature_pieceidentites.uid'], ),
    sa.ForeignKeyConstraint(['situation_administrative_uid'], ['situation_administratives.uid'], ),
    sa.ForeignKeyConstraint(['situation_matrimoniale_uid'], ['situation_matrimoniales.uid'], ),
    sa.ForeignKeyConstraint(['specialite_uid'], ['specialites.uid'], ),
    sa.ForeignKeyConstraint(['statut_uid'], ['statuts.uid'], ),
    sa.ForeignKeyConstraint(['structure_uid'], ['structures.uid'], ),
    sa.ForeignKeyConstraint(['supprime_par_uid'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['type_agent_uid'], ['type_agents.uid'], ),
    sa.ForeignKeyConstraint(['type_recrutement_uid'], ['type_recrutements.uid'], ),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['validation_fiche_uid'], ['validation_fiches.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_agents_conjoint_uid'), 'agents', ['conjoint_uid'], unique=False)
    op.create_index(op.f('ix_agents_cree_par_uid'), 'agents', ['cree_par_uid'], unique=False)
    op.create_index(op.f('ix_agents_emploi_uid'), 'agents', ['emploi_uid'], unique=False)
    op.create_index(op.f('ix_agents_fonction_uid'), 'agents', ['fonction_uid'], unique=False)
    op.create_index(op.f('ix_agents_genre_uid'), 'agents', ['genre_uid'], unique=False)
    op.create_index(op.f('ix_agents_grade_uid'), 'agents', ['grade_uid'], unique=False)
    op.create_index(op.f('ix_agents_modifie_par_uid'), 'agents', ['modifie_par_uid'], unique=False)
    op.create_index(op.f('ix_agents_nationalite_uid'), 'agents', ['nationalite_uid'], unique=False)
    op.create_index(op.f('ix_agents_nature_piece_identite_uid'), 'agents', ['nature_piece_identite_uid'], unique=False)
    op.create_index(op.f('ix_agents_situation_administrative_uid'), 'agents', ['situation_administrative_uid'], unique=False)
    op.create_index(op.f('ix_agents_situation_matrimoniale_uid'), 'agents', ['situation_matrimoniale_uid'], unique=False)
    op.create_index(op.f('ix_agents_specialite_uid'), 'agents', ['specialite_uid'], unique=False)
    op.create_index(op.f('ix_agents_statut_uid'), 'agents', ['statut_uid'], unique=False)
    op.create_index(op.f('ix_agents_structure_uid'), 'agents', ['structure_uid'], unique=False)
    op.create_index(op.f('ix_agents_supprime_par_uid'), 'agents', ['supprime_par_uid'], unique=False)
    op.create_index(op.f('ix_agents_type_agent_uid'), 'agents', ['type_agent_uid'], unique=False)
    op.create_index(op.f('ix_agents_type_recrutement_uid'), 'agents', ['type_recrutement_uid'], unique=False)
    op.create_index(op.f('ix_agents_user_uid'), 'agents', ['user_uid'], unique=False)
    op.create_index(op.f('ix_agents_validation_fiche_uid'), 'agents', ['validation_fiche_uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agents_validation_fiche_uid'), table_name='agents')
    op.drop_index(op.f('ix_agents_user_uid'), table_name='agents')
    op.drop_index(op.f('ix_agents_type_recrutement_uid'), table_name='agents')
    op.drop_index(op.f('ix_agents_type_agent_uid'), table_name='agents')
    op.drop_index(op.f('ix_agents_supprime_par_uid'), table_name='agents')
    op.drop_index(op.f('ix_agents_structure_uid'), table_name='agents')
    op.drop_index(op.f('ix_agents_statut_uid'), table_name='agents')
    op.drop_index(op.f('ix_agents_specialite_uid'), table_name='agents')
    op.drop_index(op.f('ix_agents_situation_matrimoniale_uid'), table_name='agents')
    op.drop_index(op.f('ix_agents_situation_administrative_uid'), table_name='agents')
    op.drop_index(op.f('ix_agents_nature_piece_identite_uid'), table_name='agents')
    op.drop_index(op.f('ix_agents_nationalite_uid'), table_name='agents')
    op.drop_index(op.f('ix_agents_modifie_par_uid'), table_name='agents')
    op.drop_index(op.f('ix_agents_grade_uid'), table_name='agents')
    op.drop_index(op.f('ix_agents_genre_uid'), table_name='agents')
    op.drop_index(op.f('ix_agents_fonction_uid'), table_name='agents')
    op.drop_index(op.f('ix_agents_emploi_uid'), table_name='agents')
    op.drop_index(op.f('ix_agents_cree_par_uid'), table_name='agents')
    op.drop_index(op.f('ix_agents_conjoint_uid'), table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###
