"""update Visiteur_session fileds

Revision ID: 3b525ff6966e
Revises: 4f3c2a1b0d9e
Create Date: 2026-09-06 12:21:52.369302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b525ff6966e'
down_revision: Union[str, Sequence[str], None] = '4f3c2a1b0d9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
