"""add phototheque fichier_key fields

Revision ID: 4499bfaffc99
Revises: bd67b03d99fb
Create Date: 2026-09-03 19:32:40.075522

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4499bfaffc99'
down_revision: Union[str, Sequence[str], None] = 'bd67b03d99fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actualites', sa.Column('fichier_key', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.add_column('communiques', sa.Column('fichier_key', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.alter_column('communiques', 'est_epingle',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('communiques', 'nombre_telechargements',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('services', sa.Column('fichier_key', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.alter_column('services', 'ordre_affichage',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_services_est_en_ligne'), table_name='services')
    op.drop_index(op.f('ix_services_est_mis_en_avant'), table_name='services')
    op.drop_column('services', 'est_mis_en_avant')
    op.drop_column('services', 'est_en_ligne')
    op.drop_column('services', 'procedure')
    op.drop_column('services', 'conditions_acces')
    op.drop_column('services', 'pieces_requises')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('pieces_requises', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('services', sa.Column('conditions_acces', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('services', sa.Column('procedure', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('services', sa.Column('est_en_ligne', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('services', sa.Column('est_mis_en_avant', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_services_est_mis_en_avant'), 'services', ['est_mis_en_avant'], unique=False)
    op.create_index(op.f('ix_services_est_en_ligne'), 'services', ['est_en_ligne'], unique=False)
    op.alter_column('services', 'ordre_affichage',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('services', 'fichier_key')
    op.alter_column('communiques', 'nombre_telechargements',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('communiques', 'est_epingle',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('communiques', 'fichier_key')
    op.drop_column('actualites', 'fichier_key')
    # ### end Alembic commands ###
