"""update message table fields des dates

Revision ID: 45f1e37593a8
Revises: 8d2d2172f5fe
Create Date: 2026-09-04 19:41:59.889584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '45f1e37593a8'
down_revision: Union[str, Sequence[str], None] = '8d2d2172f5fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'envoye_le',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index(op.f('ix_messages_envoye_le'), table_name='messages')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_messages_envoye_le'), 'messages', ['envoye_le'], unique=False)
    op.alter_column('messages', 'envoye_le',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
