"""update message table fields

Revision ID: 4cef72e1139e
Revises: 4499bfaffc99
Create Date: 2026-09-04 13:11:40.350141

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4cef72e1139e'
down_revision: Union[str, Sequence[str], None] = '4499bfaffc99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('nom_prenoms_expediteur', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('messages', sa.Column('service_expediteur', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.alter_column('messages', 'est_important',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('messages', 'est_epingle',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('messages', 'est_lu',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('messages', 'envoye_le',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('messages', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('messages', 'envoye_le',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('messages', 'est_lu',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('messages', 'est_epingle',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('messages', 'est_important',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('messages', 'service_expediteur')
    op.drop_column('messages', 'nom_prenoms_expediteur')
    # ### end Alembic commands ###
