"""update nature_nomination_fonctionactuelles 

Revision ID: 4e02cd8a8ee3
Revises: 07362f84d043
Create Date: 2026-08-18 23:00:01.198608

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e02cd8a8ee3'
down_revision: Union[str, Sequence[str], None] = '07362f84d043'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nature_acte_nomination_fonctionactuelles',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_mode', sa.Boolean(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('supprime_le', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.drop_table('nature_acte_nomination_fonctionactuelle')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nature_acte_nomination_fonctionactuelle',
    sa.Column('uid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('libelle', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('cree_le', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('modifie_le', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_mode', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_delete', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('supprime_le', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('uid', name=op.f('nature_acte_nomination_fonctionactuelle_pkey'))
    )
    op.drop_table('nature_acte_nomination_fonctionactuelles')
    # ### end Alembic commands ###
