"""update statut_agents 

Revision ID: 4f7695183cbe
Revises: 4e02cd8a8ee3
Create Date: 2026-08-19 00:13:57.855772

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f7695183cbe'
down_revision: Union[str, Sequence[str], None] = '4e02cd8a8ee3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statut_agents',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_mode', sa.Boolean(), nullable=True),
    sa.Column('supprime_le', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.add_column('enseignants', sa.Column('type_agent_uid', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_enseignants_type_agent_uid'), 'enseignants', ['type_agent_uid'], unique=False)
    op.create_foreign_key(None, 'enseignants', 'type_agents', ['type_agent_uid'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'enseignants', type_='foreignkey')
    op.drop_index(op.f('ix_enseignants_type_agent_uid'), table_name='enseignants')
    op.drop_column('enseignants', 'type_agent_uid')
    op.drop_table('statut_agents')
    # ### end Alembic commands ###
