"""add user status fields

Revision ID: 50fd3fe49a11
Revises: 
Create Date: 2026-08-17 20:58:53.581590

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50fd3fe49a11'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ordre', sa.Integer(), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_mode', sa.Boolean(), nullable=True),
    sa.Column('supprime_le', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('roles',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_mode', sa.Boolean(), nullable=True),
    sa.Column('supprime_le', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('statut_affectations',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_mode', sa.Boolean(), nullable=True),
    sa.Column('supprime_le', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('statut_eleves',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_mode', sa.Boolean(), nullable=True),
    sa.Column('supprime_le', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('type_etablissements',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_mode', sa.Boolean(), nullable=True),
    sa.Column('supprime_le', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('users',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('role_uid', sa.Uuid(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modifier_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('supprime_le', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['role_uid'], ['roles.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_users_role_uid'), 'users', ['role_uid'], unique=False)
    op.create_table('auth_sessions',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('user_uid', sa.Uuid(), nullable=True),
    sa.Column('refresh_token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('diplomes',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cree_par', sa.Uuid(), nullable=True),
    sa.Column('modifie_par', sa.Uuid(), nullable=True),
    sa.Column('supprime_par', sa.Uuid(), nullable=True),
    sa.Column('is_mode', sa.Boolean(), nullable=True),
    sa.Column('supprime_le', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cree_par'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['modifie_par'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['supprime_par'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_diplomes_cree_par'), 'diplomes', ['cree_par'], unique=False)
    op.create_index(op.f('ix_diplomes_modifie_par'), 'diplomes', ['modifie_par'], unique=False)
    op.create_index(op.f('ix_diplomes_supprime_par'), 'diplomes', ['supprime_par'], unique=False)
    op.create_table('domaine_resaos',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cree_par', sa.Uuid(), nullable=True),
    sa.Column('modifie_par', sa.Uuid(), nullable=True),
    sa.Column('supprime_par', sa.Uuid(), nullable=True),
    sa.Column('is_mode', sa.Boolean(), nullable=True),
    sa.Column('supprime_le', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cree_par'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['modifie_par'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['supprime_par'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_domaine_resaos_cree_par'), 'domaine_resaos', ['cree_par'], unique=False)
    op.create_index(op.f('ix_domaine_resaos_modifie_par'), 'domaine_resaos', ['modifie_par'], unique=False)
    op.create_index(op.f('ix_domaine_resaos_supprime_par'), 'domaine_resaos', ['supprime_par'], unique=False)
    op.create_table('etablissements',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('abreviation', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('identifiantofficiel', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('personne_contact', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('telephone_personne_contact', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('anneecreation', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('quartier', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('adressecomplete', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('telephone', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('siteweb', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cree_par', sa.Uuid(), nullable=True),
    sa.Column('modifie_par', sa.Uuid(), nullable=True),
    sa.Column('supprime_par', sa.Uuid(), nullable=True),
    sa.Column('is_mode', sa.Boolean(), nullable=True),
    sa.Column('supprime_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('responsable_etablissement_uid', sa.Uuid(), nullable=True),
    sa.Column('statut_etablissement', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('type_etablissement', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['cree_par'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['modifie_par'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['responsable_etablissement_uid'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['supprime_par'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_etablissements_cree_par'), 'etablissements', ['cree_par'], unique=False)
    op.create_index(op.f('ix_etablissements_modifie_par'), 'etablissements', ['modifie_par'], unique=False)
    op.create_index(op.f('ix_etablissements_responsable_etablissement_uid'), 'etablissements', ['responsable_etablissement_uid'], unique=False)
    op.create_index(op.f('ix_etablissements_supprime_par'), 'etablissements', ['supprime_par'], unique=False)
    op.create_table('facultes',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cree_par', sa.Uuid(), nullable=True),
    sa.Column('modifie_par', sa.Uuid(), nullable=True),
    sa.Column('supprime_par', sa.Uuid(), nullable=True),
    sa.Column('is_mode', sa.Boolean(), nullable=True),
    sa.Column('supprime_le', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cree_par'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['modifie_par'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['supprime_par'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_facultes_cree_par'), 'facultes', ['cree_par'], unique=False)
    op.create_index(op.f('ix_facultes_modifie_par'), 'facultes', ['modifie_par'], unique=False)
    op.create_index(op.f('ix_facultes_supprime_par'), 'facultes', ['supprime_par'], unique=False)
    op.create_table('fonctions',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cree_par', sa.Uuid(), nullable=True),
    sa.Column('modifie_par', sa.Uuid(), nullable=True),
    sa.Column('supprime_par', sa.Uuid(), nullable=True),
    sa.Column('is_mode', sa.Boolean(), nullable=True),
    sa.Column('supprime_le', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cree_par'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['modifie_par'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['supprime_par'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_fonctions_cree_par'), 'fonctions', ['cree_par'], unique=False)
    op.create_index(op.f('ix_fonctions_modifie_par'), 'fonctions', ['modifie_par'], unique=False)
    op.create_index(op.f('ix_fonctions_supprime_par'), 'fonctions', ['supprime_par'], unique=False)
    op.create_table('genres',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cree_par', sa.Uuid(), nullable=True),
    sa.Column('modifie_par', sa.Uuid(), nullable=True),
    sa.Column('supprime_par', sa.Uuid(), nullable=True),
    sa.Column('is_mode', sa.Boolean(), nullable=True),
    sa.Column('supprime_le', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cree_par'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['modifie_par'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['supprime_par'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_genres_cree_par'), 'genres', ['cree_par'], unique=False)
    op.create_index(op.f('ix_genres_modifie_par'), 'genres', ['modifie_par'], unique=False)
    op.create_index(op.f('ix_genres_supprime_par'), 'genres', ['supprime_par'], unique=False)
    op.create_table('grades',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cree_par', sa.Uuid(), nullable=True),
    sa.Column('modifie_par', sa.Uuid(), nullable=True),
    sa.Column('supprime_par', sa.Uuid(), nullable=True),
    sa.Column('is_mode', sa.Boolean(), nullable=True),
    sa.Column('supprime_le', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cree_par'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['modifie_par'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['supprime_par'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_grades_cree_par'), 'grades', ['cree_par'], unique=False)
    op.create_index(op.f('ix_grades_modifie_par'), 'grades', ['modifie_par'], unique=False)
    op.create_index(op.f('ix_grades_supprime_par'), 'grades', ['supprime_par'], unique=False)
    op.create_table('groupe_emplois',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cree_par', sa.Uuid(), nullable=True),
    sa.Column('modifie_par', sa.Uuid(), nullable=True),
    sa.Column('supprime_par', sa.Uuid(), nullable=True),
    sa.Column('is_mode', sa.Boolean(), nullable=True),
    sa.Column('supprime_le', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cree_par'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['modifie_par'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['supprime_par'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_groupe_emplois_cree_par'), 'groupe_emplois', ['cree_par'], unique=False)
    op.create_index(op.f('ix_groupe_emplois_modifie_par'), 'groupe_emplois', ['modifie_par'], unique=False)
    op.create_index(op.f('ix_groupe_emplois_supprime_par'), 'groupe_emplois', ['supprime_par'], unique=False)
    op.create_table('groupes',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cree_par', sa.Uuid(), nullable=True),
    sa.Column('modifie_par', sa.Uuid(), nullable=True),
    sa.Column('supprime_par', sa.Uuid(), nullable=True),
    sa.Column('is_mode', sa.Boolean(), nullable=True),
    sa.Column('supprime_le', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cree_par'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['modifie_par'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['supprime_par'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_groupes_cree_par'), 'groupes', ['cree_par'], unique=False)
    op.create_index(op.f('ix_groupes_modifie_par'), 'groupes', ['modifie_par'], unique=False)
    op.create_index(op.f('ix_groupes_supprime_par'), 'groupes', ['supprime_par'], unique=False)
    op.create_table('login_attempt_states',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('nationalites',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cree_par', sa.Uuid(), nullable=True),
    sa.Column('modifie_par', sa.Uuid(), nullable=True),
    sa.Column('supprime_par', sa.Uuid(), nullable=True),
    sa.Column('is_mode', sa.Boolean(), nullable=True),
    sa.Column('supprime_le', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cree_par'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['modifie_par'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['supprime_par'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_nationalites_cree_par'), 'nationalites', ['cree_par'], unique=False)
    op.create_index(op.f('ix_nationalites_modifie_par'), 'nationalites', ['modifie_par'], unique=False)
    op.create_index(op.f('ix_nationalites_supprime_par'), 'nationalites', ['supprime_par'], unique=False)
    op.create_table('niveaux',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cree_par', sa.Uuid(), nullable=True),
    sa.Column('modifie_par', sa.Uuid(), nullable=True),
    sa.Column('supprime_par', sa.Uuid(), nullable=True),
    sa.Column('is_mode', sa.Boolean(), nullable=True),
    sa.Column('supprime_le', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cree_par'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['modifie_par'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['supprime_par'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_niveaux_cree_par'), 'niveaux', ['cree_par'], unique=False)
    op.create_index(op.f('ix_niveaux_modifie_par'), 'niveaux', ['modifie_par'], unique=False)
    op.create_index(op.f('ix_niveaux_supprime_par'), 'niveaux', ['supprime_par'], unique=False)
    op.create_table('parcours',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cree_par', sa.Uuid(), nullable=True),
    sa.Column('modifie_par', sa.Uuid(), nullable=True),
    sa.Column('supprime_par', sa.Uuid(), nullable=True),
    sa.Column('is_mode', sa.Boolean(), nullable=True),
    sa.Column('supprime_le', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cree_par'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['modifie_par'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['supprime_par'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_parcours_cree_par'), 'parcours', ['cree_par'], unique=False)
    op.create_index(op.f('ix_parcours_modifie_par'), 'parcours', ['modifie_par'], unique=False)
    op.create_index(op.f('ix_parcours_supprime_par'), 'parcours', ['supprime_par'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('promotions',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cree_par', sa.Uuid(), nullable=True),
    sa.Column('modifie_par', sa.Uuid(), nullable=True),
    sa.Column('supprime_par', sa.Uuid(), nullable=True),
    sa.Column('is_mode', sa.Boolean(), nullable=True),
    sa.Column('supprime_le', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cree_par'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['modifie_par'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['supprime_par'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_promotions_cree_par'), 'promotions', ['cree_par'], unique=False)
    op.create_index(op.f('ix_promotions_modifie_par'), 'promotions', ['modifie_par'], unique=False)
    op.create_index(op.f('ix_promotions_supprime_par'), 'promotions', ['supprime_par'], unique=False)
    op.create_table('statuts',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cree_par', sa.Uuid(), nullable=True),
    sa.Column('modifie_par', sa.Uuid(), nullable=True),
    sa.Column('supprime_par', sa.Uuid(), nullable=True),
    sa.Column('is_mode', sa.Boolean(), nullable=True),
    sa.Column('supprime_le', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cree_par'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['modifie_par'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['supprime_par'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_statuts_cree_par'), 'statuts', ['cree_par'], unique=False)
    op.create_index(op.f('ix_statuts_modifie_par'), 'statuts', ['modifie_par'], unique=False)
    op.create_index(op.f('ix_statuts_supprime_par'), 'statuts', ['supprime_par'], unique=False)
    op.create_table('type_emplois',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cree_par', sa.Uuid(), nullable=True),
    sa.Column('modifie_par', sa.Uuid(), nullable=True),
    sa.Column('supprime_par', sa.Uuid(), nullable=True),
    sa.Column('is_mode', sa.Boolean(), nullable=True),
    sa.Column('supprime_le', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cree_par'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['modifie_par'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['supprime_par'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_type_emplois_cree_par'), 'type_emplois', ['cree_par'], unique=False)
    op.create_index(op.f('ix_type_emplois_modifie_par'), 'type_emplois', ['modifie_par'], unique=False)
    op.create_index(op.f('ix_type_emplois_supprime_par'), 'type_emplois', ['supprime_par'], unique=False)
    op.create_table('type_recrutements',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cree_par', sa.Uuid(), nullable=True),
    sa.Column('modifie_par', sa.Uuid(), nullable=True),
    sa.Column('supprime_par', sa.Uuid(), nullable=True),
    sa.Column('is_mode', sa.Boolean(), nullable=True),
    sa.Column('supprime_le', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cree_par'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['modifie_par'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['supprime_par'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_type_recrutements_cree_par'), 'type_recrutements', ['cree_par'], unique=False)
    op.create_index(op.f('ix_type_recrutements_modifie_par'), 'type_recrutements', ['modifie_par'], unique=False)
    op.create_index(op.f('ix_type_recrutements_supprime_par'), 'type_recrutements', ['supprime_par'], unique=False)
    op.create_table('type_structures',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cree_par', sa.Uuid(), nullable=True),
    sa.Column('modifie_par', sa.Uuid(), nullable=True),
    sa.Column('supprime_par', sa.Uuid(), nullable=True),
    sa.Column('is_mode', sa.Boolean(), nullable=True),
    sa.Column('supprime_le', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cree_par'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['modifie_par'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['supprime_par'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_type_structures_cree_par'), 'type_structures', ['cree_par'], unique=False)
    op.create_index(op.f('ix_type_structures_modifie_par'), 'type_structures', ['modifie_par'], unique=False)
    op.create_index(op.f('ix_type_structures_supprime_par'), 'type_structures', ['supprime_par'], unique=False)
    op.create_table('user_permissions',
    sa.Column('user_uid', sa.Uuid(), nullable=False),
    sa.Column('permission_uid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['permission_uid'], ['permissions.uid'], ),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('user_uid', 'permission_uid')
    )
    op.create_table('disciplines',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cree_par', sa.Uuid(), nullable=True),
    sa.Column('modifie_par', sa.Uuid(), nullable=True),
    sa.Column('supprime_par', sa.Uuid(), nullable=True),
    sa.Column('is_mode', sa.Boolean(), nullable=True),
    sa.Column('supprime_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('domaine_resao_uid', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['cree_par'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['domaine_resao_uid'], ['domaine_resaos.uid'], ),
    sa.ForeignKeyConstraint(['modifie_par'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['supprime_par'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_disciplines_cree_par'), 'disciplines', ['cree_par'], unique=False)
    op.create_index(op.f('ix_disciplines_domaine_resao_uid'), 'disciplines', ['domaine_resao_uid'], unique=False)
    op.create_index(op.f('ix_disciplines_modifie_par'), 'disciplines', ['modifie_par'], unique=False)
    op.create_index(op.f('ix_disciplines_supprime_par'), 'disciplines', ['supprime_par'], unique=False)
    op.create_table('emplois',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cree_par', sa.Uuid(), nullable=True),
    sa.Column('modifie_par', sa.Uuid(), nullable=True),
    sa.Column('supprime_par', sa.Uuid(), nullable=True),
    sa.Column('is_mode', sa.Boolean(), nullable=True),
    sa.Column('supprime_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('type_emploi_uid', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['cree_par'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['modifie_par'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['supprime_par'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['type_emploi_uid'], ['type_emplois.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_emplois_cree_par'), 'emplois', ['cree_par'], unique=False)
    op.create_index(op.f('ix_emplois_modifie_par'), 'emplois', ['modifie_par'], unique=False)
    op.create_index(op.f('ix_emplois_supprime_par'), 'emplois', ['supprime_par'], unique=False)
    op.create_table('structures',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('abreviation', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_mode', sa.Boolean(), nullable=True),
    sa.Column('supprime_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('personne_contact', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('telephone_personne_contact', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('anneecreation', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('quartier', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('adressecomplete', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('telephone', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('siteweb', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('type_structure_uid', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['type_structure_uid'], ['type_structures.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_structures_type_structure_uid'), 'structures', ['type_structure_uid'], unique=False)
    op.create_table('departements',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cree_par', sa.Uuid(), nullable=True),
    sa.Column('modifie_par', sa.Uuid(), nullable=True),
    sa.Column('supprime_par', sa.Uuid(), nullable=True),
    sa.Column('is_mode', sa.Boolean(), nullable=True),
    sa.Column('supprime_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('structure_uid', sa.Uuid(), nullable=True),
    sa.Column('faculte_uid', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['cree_par'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['faculte_uid'], ['facultes.uid'], ),
    sa.ForeignKeyConstraint(['modifie_par'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['structure_uid'], ['structures.uid'], ),
    sa.ForeignKeyConstraint(['supprime_par'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_departements_cree_par'), 'departements', ['cree_par'], unique=False)
    op.create_index(op.f('ix_departements_faculte_uid'), 'departements', ['faculte_uid'], unique=False)
    op.create_index(op.f('ix_departements_modifie_par'), 'departements', ['modifie_par'], unique=False)
    op.create_index(op.f('ix_departements_structure_uid'), 'departements', ['structure_uid'], unique=False)
    op.create_index(op.f('ix_departements_supprime_par'), 'departements', ['supprime_par'], unique=False)
    op.create_table('specialites',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cree_par', sa.Uuid(), nullable=True),
    sa.Column('modifie_par', sa.Uuid(), nullable=True),
    sa.Column('supprime_par', sa.Uuid(), nullable=True),
    sa.Column('is_mode', sa.Boolean(), nullable=True),
    sa.Column('supprime_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discipline_uid', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['cree_par'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['discipline_uid'], ['disciplines.uid'], ),
    sa.ForeignKeyConstraint(['modifie_par'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['supprime_par'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_specialites_cree_par'), 'specialites', ['cree_par'], unique=False)
    op.create_index(op.f('ix_specialites_discipline_uid'), 'specialites', ['discipline_uid'], unique=False)
    op.create_index(op.f('ix_specialites_modifie_par'), 'specialites', ['modifie_par'], unique=False)
    op.create_index(op.f('ix_specialites_supprime_par'), 'specialites', ['supprime_par'], unique=False)
    op.create_table('enseignants',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('prenoms', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('matricule', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('date_naissance', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lieu_naissance', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('telephone_principal', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('telephone_secondaire', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('email_professionnel', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('email_personneö', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('quartier', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('lieu_habitation', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('date_recrutement', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_depart', sa.DateTime(timezone=True), nullable=True),
    sa.Column('nombre_enfant', sa.Integer(), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cree_par_uid', sa.Uuid(), nullable=True),
    sa.Column('modifie_par_uid', sa.Uuid(), nullable=True),
    sa.Column('supprime_par_uid', sa.Uuid(), nullable=True),
    sa.Column('is_mode', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('supprime_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_premiere_prise_service_dans_structure', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_premiere_prise_service_fonction_publique', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fonction_uid', sa.Uuid(), nullable=True),
    sa.Column('genre_uid', sa.Uuid(), nullable=True),
    sa.Column('user_uid', sa.Uuid(), nullable=True),
    sa.Column('nationalite_uid', sa.Uuid(), nullable=True),
    sa.Column('type_recrutement_uid', sa.Uuid(), nullable=True),
    sa.Column('structure_uid', sa.Uuid(), nullable=True),
    sa.Column('specialite_uid', sa.Uuid(), nullable=True),
    sa.Column('diplome_uid', sa.Uuid(), nullable=True),
    sa.Column('emploi_uid', sa.Uuid(), nullable=True),
    sa.Column('grade_uid', sa.Uuid(), nullable=True),
    sa.Column('statut_uid', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['cree_par_uid'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['diplome_uid'], ['diplomes.uid'], ),
    sa.ForeignKeyConstraint(['emploi_uid'], ['emplois.uid'], ),
    sa.ForeignKeyConstraint(['fonction_uid'], ['fonctions.uid'], ),
    sa.ForeignKeyConstraint(['genre_uid'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['grade_uid'], ['grades.uid'], ),
    sa.ForeignKeyConstraint(['modifie_par_uid'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['nationalite_uid'], ['nationalites.uid'], ),
    sa.ForeignKeyConstraint(['specialite_uid'], ['specialites.uid'], ),
    sa.ForeignKeyConstraint(['statut_uid'], ['statuts.uid'], ),
    sa.ForeignKeyConstraint(['structure_uid'], ['structures.uid'], ),
    sa.ForeignKeyConstraint(['supprime_par_uid'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['type_recrutement_uid'], ['type_recrutements.uid'], ),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_enseignants_cree_par_uid'), 'enseignants', ['cree_par_uid'], unique=False)
    op.create_index(op.f('ix_enseignants_diplome_uid'), 'enseignants', ['diplome_uid'], unique=False)
    op.create_index(op.f('ix_enseignants_emploi_uid'), 'enseignants', ['emploi_uid'], unique=False)
    op.create_index(op.f('ix_enseignants_fonction_uid'), 'enseignants', ['fonction_uid'], unique=False)
    op.create_index(op.f('ix_enseignants_genre_uid'), 'enseignants', ['genre_uid'], unique=False)
    op.create_index(op.f('ix_enseignants_grade_uid'), 'enseignants', ['grade_uid'], unique=False)
    op.create_index(op.f('ix_enseignants_modifie_par_uid'), 'enseignants', ['modifie_par_uid'], unique=False)
    op.create_index(op.f('ix_enseignants_nationalite_uid'), 'enseignants', ['nationalite_uid'], unique=False)
    op.create_index(op.f('ix_enseignants_specialite_uid'), 'enseignants', ['specialite_uid'], unique=False)
    op.create_index(op.f('ix_enseignants_statut_uid'), 'enseignants', ['statut_uid'], unique=False)
    op.create_index(op.f('ix_enseignants_structure_uid'), 'enseignants', ['structure_uid'], unique=False)
    op.create_index(op.f('ix_enseignants_supprime_par_uid'), 'enseignants', ['supprime_par_uid'], unique=False)
    op.create_index(op.f('ix_enseignants_type_recrutement_uid'), 'enseignants', ['type_recrutement_uid'], unique=False)
    op.create_index(op.f('ix_enseignants_user_uid'), 'enseignants', ['user_uid'], unique=False)
    op.create_table('filieres',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cree_par', sa.Uuid(), nullable=True),
    sa.Column('modifie_par', sa.Uuid(), nullable=True),
    sa.Column('supprime_par', sa.Uuid(), nullable=True),
    sa.Column('is_mode', sa.Boolean(), nullable=True),
    sa.Column('supprime_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('specialite_uid', sa.Uuid(), nullable=True),
    sa.Column('departement_uid', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['cree_par'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['departement_uid'], ['departements.uid'], ),
    sa.ForeignKeyConstraint(['modifie_par'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['specialite_uid'], ['specialites.uid'], ),
    sa.ForeignKeyConstraint(['supprime_par'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_filieres_cree_par'), 'filieres', ['cree_par'], unique=False)
    op.create_index(op.f('ix_filieres_modifie_par'), 'filieres', ['modifie_par'], unique=False)
    op.create_index(op.f('ix_filieres_supprime_par'), 'filieres', ['supprime_par'], unique=False)
    op.create_table('eleves',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('prenoms', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('matricule', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('date_naissance', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lieu_naissance', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('numero_table', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('statut_affectation_uid', sa.Uuid(), nullable=True),
    sa.Column('statut_eleve_uid', sa.Uuid(), nullable=True),
    sa.Column('genre_uid', sa.Uuid(), nullable=True),
    sa.Column('groupe_uid', sa.Uuid(), nullable=True),
    sa.Column('nuveau_uid', sa.Uuid(), nullable=True),
    sa.Column('promotion_uid', sa.Uuid(), nullable=True),
    sa.Column('filieres_uid', sa.Uuid(), nullable=True),
    sa.Column('etablissement_uid', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_mode', sa.Boolean(), nullable=False),
    sa.Column('user_uid', sa.Uuid(), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cree_par_uid', sa.Uuid(), nullable=True),
    sa.Column('modifie_par_uid', sa.Uuid(), nullable=True),
    sa.Column('supprime_par_uid', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('supprime_le', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cree_par_uid'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['etablissement_uid'], ['etablissements.uid'], ),
    sa.ForeignKeyConstraint(['filieres_uid'], ['filieres.uid'], ),
    sa.ForeignKeyConstraint(['genre_uid'], ['genres.uid'], ),
    sa.ForeignKeyConstraint(['groupe_uid'], ['groupes.uid'], ),
    sa.ForeignKeyConstraint(['modifie_par_uid'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['nuveau_uid'], ['niveaux.uid'], ),
    sa.ForeignKeyConstraint(['promotion_uid'], ['promotions.uid'], ),
    sa.ForeignKeyConstraint(['statut_affectation_uid'], ['statut_affectations.uid'], ),
    sa.ForeignKeyConstraint(['statut_eleve_uid'], ['statut_eleves.uid'], ),
    sa.ForeignKeyConstraint(['supprime_par_uid'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_eleves_cree_par_uid'), 'eleves', ['cree_par_uid'], unique=False)
    op.create_index(op.f('ix_eleves_modifie_par_uid'), 'eleves', ['modifie_par_uid'], unique=False)
    op.create_index(op.f('ix_eleves_supprime_par_uid'), 'eleves', ['supprime_par_uid'], unique=False)
    op.create_index(op.f('ix_eleves_user_uid'), 'eleves', ['user_uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_eleves_user_uid'), table_name='eleves')
    op.drop_index(op.f('ix_eleves_supprime_par_uid'), table_name='eleves')
    op.drop_index(op.f('ix_eleves_modifie_par_uid'), table_name='eleves')
    op.drop_index(op.f('ix_eleves_cree_par_uid'), table_name='eleves')
    op.drop_table('eleves')
    op.drop_index(op.f('ix_filieres_supprime_par'), table_name='filieres')
    op.drop_index(op.f('ix_filieres_modifie_par'), table_name='filieres')
    op.drop_index(op.f('ix_filieres_cree_par'), table_name='filieres')
    op.drop_table('filieres')
    op.drop_index(op.f('ix_enseignants_user_uid'), table_name='enseignants')
    op.drop_index(op.f('ix_enseignants_type_recrutement_uid'), table_name='enseignants')
    op.drop_index(op.f('ix_enseignants_supprime_par_uid'), table_name='enseignants')
    op.drop_index(op.f('ix_enseignants_structure_uid'), table_name='enseignants')
    op.drop_index(op.f('ix_enseignants_statut_uid'), table_name='enseignants')
    op.drop_index(op.f('ix_enseignants_specialite_uid'), table_name='enseignants')
    op.drop_index(op.f('ix_enseignants_nationalite_uid'), table_name='enseignants')
    op.drop_index(op.f('ix_enseignants_modifie_par_uid'), table_name='enseignants')
    op.drop_index(op.f('ix_enseignants_grade_uid'), table_name='enseignants')
    op.drop_index(op.f('ix_enseignants_genre_uid'), table_name='enseignants')
    op.drop_index(op.f('ix_enseignants_fonction_uid'), table_name='enseignants')
    op.drop_index(op.f('ix_enseignants_emploi_uid'), table_name='enseignants')
    op.drop_index(op.f('ix_enseignants_diplome_uid'), table_name='enseignants')
    op.drop_index(op.f('ix_enseignants_cree_par_uid'), table_name='enseignants')
    op.drop_table('enseignants')
    op.drop_index(op.f('ix_specialites_supprime_par'), table_name='specialites')
    op.drop_index(op.f('ix_specialites_modifie_par'), table_name='specialites')
    op.drop_index(op.f('ix_specialites_discipline_uid'), table_name='specialites')
    op.drop_index(op.f('ix_specialites_cree_par'), table_name='specialites')
    op.drop_table('specialites')
    op.drop_index(op.f('ix_departements_supprime_par'), table_name='departements')
    op.drop_index(op.f('ix_departements_structure_uid'), table_name='departements')
    op.drop_index(op.f('ix_departements_modifie_par'), table_name='departements')
    op.drop_index(op.f('ix_departements_faculte_uid'), table_name='departements')
    op.drop_index(op.f('ix_departements_cree_par'), table_name='departements')
    op.drop_table('departements')
    op.drop_index(op.f('ix_structures_type_structure_uid'), table_name='structures')
    op.drop_table('structures')
    op.drop_index(op.f('ix_emplois_supprime_par'), table_name='emplois')
    op.drop_index(op.f('ix_emplois_modifie_par'), table_name='emplois')
    op.drop_index(op.f('ix_emplois_cree_par'), table_name='emplois')
    op.drop_table('emplois')
    op.drop_index(op.f('ix_disciplines_supprime_par'), table_name='disciplines')
    op.drop_index(op.f('ix_disciplines_modifie_par'), table_name='disciplines')
    op.drop_index(op.f('ix_disciplines_domaine_resao_uid'), table_name='disciplines')
    op.drop_index(op.f('ix_disciplines_cree_par'), table_name='disciplines')
    op.drop_table('disciplines')
    op.drop_table('user_permissions')
    op.drop_index(op.f('ix_type_structures_supprime_par'), table_name='type_structures')
    op.drop_index(op.f('ix_type_structures_modifie_par'), table_name='type_structures')
    op.drop_index(op.f('ix_type_structures_cree_par'), table_name='type_structures')
    op.drop_table('type_structures')
    op.drop_index(op.f('ix_type_recrutements_supprime_par'), table_name='type_recrutements')
    op.drop_index(op.f('ix_type_recrutements_modifie_par'), table_name='type_recrutements')
    op.drop_index(op.f('ix_type_recrutements_cree_par'), table_name='type_recrutements')
    op.drop_table('type_recrutements')
    op.drop_index(op.f('ix_type_emplois_supprime_par'), table_name='type_emplois')
    op.drop_index(op.f('ix_type_emplois_modifie_par'), table_name='type_emplois')
    op.drop_index(op.f('ix_type_emplois_cree_par'), table_name='type_emplois')
    op.drop_table('type_emplois')
    op.drop_index(op.f('ix_statuts_supprime_par'), table_name='statuts')
    op.drop_index(op.f('ix_statuts_modifie_par'), table_name='statuts')
    op.drop_index(op.f('ix_statuts_cree_par'), table_name='statuts')
    op.drop_table('statuts')
    op.drop_index(op.f('ix_promotions_supprime_par'), table_name='promotions')
    op.drop_index(op.f('ix_promotions_modifie_par'), table_name='promotions')
    op.drop_index(op.f('ix_promotions_cree_par'), table_name='promotions')
    op.drop_table('promotions')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_parcours_supprime_par'), table_name='parcours')
    op.drop_index(op.f('ix_parcours_modifie_par'), table_name='parcours')
    op.drop_index(op.f('ix_parcours_cree_par'), table_name='parcours')
    op.drop_table('parcours')
    op.drop_index(op.f('ix_niveaux_supprime_par'), table_name='niveaux')
    op.drop_index(op.f('ix_niveaux_modifie_par'), table_name='niveaux')
    op.drop_index(op.f('ix_niveaux_cree_par'), table_name='niveaux')
    op.drop_table('niveaux')
    op.drop_index(op.f('ix_nationalites_supprime_par'), table_name='nationalites')
    op.drop_index(op.f('ix_nationalites_modifie_par'), table_name='nationalites')
    op.drop_index(op.f('ix_nationalites_cree_par'), table_name='nationalites')
    op.drop_table('nationalites')
    op.drop_table('login_attempt_states')
    op.drop_index(op.f('ix_groupes_supprime_par'), table_name='groupes')
    op.drop_index(op.f('ix_groupes_modifie_par'), table_name='groupes')
    op.drop_index(op.f('ix_groupes_cree_par'), table_name='groupes')
    op.drop_table('groupes')
    op.drop_index(op.f('ix_groupe_emplois_supprime_par'), table_name='groupe_emplois')
    op.drop_index(op.f('ix_groupe_emplois_modifie_par'), table_name='groupe_emplois')
    op.drop_index(op.f('ix_groupe_emplois_cree_par'), table_name='groupe_emplois')
    op.drop_table('groupe_emplois')
    op.drop_index(op.f('ix_grades_supprime_par'), table_name='grades')
    op.drop_index(op.f('ix_grades_modifie_par'), table_name='grades')
    op.drop_index(op.f('ix_grades_cree_par'), table_name='grades')
    op.drop_table('grades')
    op.drop_index(op.f('ix_genres_supprime_par'), table_name='genres')
    op.drop_index(op.f('ix_genres_modifie_par'), table_name='genres')
    op.drop_index(op.f('ix_genres_cree_par'), table_name='genres')
    op.drop_table('genres')
    op.drop_index(op.f('ix_fonctions_supprime_par'), table_name='fonctions')
    op.drop_index(op.f('ix_fonctions_modifie_par'), table_name='fonctions')
    op.drop_index(op.f('ix_fonctions_cree_par'), table_name='fonctions')
    op.drop_table('fonctions')
    op.drop_index(op.f('ix_facultes_supprime_par'), table_name='facultes')
    op.drop_index(op.f('ix_facultes_modifie_par'), table_name='facultes')
    op.drop_index(op.f('ix_facultes_cree_par'), table_name='facultes')
    op.drop_table('facultes')
    op.drop_index(op.f('ix_etablissements_supprime_par'), table_name='etablissements')
    op.drop_index(op.f('ix_etablissements_responsable_etablissement_uid'), table_name='etablissements')
    op.drop_index(op.f('ix_etablissements_modifie_par'), table_name='etablissements')
    op.drop_index(op.f('ix_etablissements_cree_par'), table_name='etablissements')
    op.drop_table('etablissements')
    op.drop_index(op.f('ix_domaine_resaos_supprime_par'), table_name='domaine_resaos')
    op.drop_index(op.f('ix_domaine_resaos_modifie_par'), table_name='domaine_resaos')
    op.drop_index(op.f('ix_domaine_resaos_cree_par'), table_name='domaine_resaos')
    op.drop_table('domaine_resaos')
    op.drop_index(op.f('ix_diplomes_supprime_par'), table_name='diplomes')
    op.drop_index(op.f('ix_diplomes_modifie_par'), table_name='diplomes')
    op.drop_index(op.f('ix_diplomes_cree_par'), table_name='diplomes')
    op.drop_table('diplomes')
    op.drop_table('auth_sessions')
    op.drop_index(op.f('ix_users_role_uid'), table_name='users')
    op.drop_table('users')
    op.drop_table('type_etablissements')
    op.drop_table('statut_eleves')
    op.drop_table('statut_affectations')
    op.drop_table('roles')
    op.drop_table('permissions')
    # ### end Alembic commands ###
