"""update categorie_phototheque fields avec None

Revision ID: 52927702f50e
Revises: 822d4339d0e7
Create Date: 2026-09-02 09:05:34.253990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '52927702f50e'
down_revision: Union[str, Sequence[str], None] = '822d4339d0e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories_phototheques', 'cree_le',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('categories_phototheques', 'modifie_le',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('categories_phototheques', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories_phototheques', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('categories_phototheques', 'modifie_le',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('categories_phototheques', 'cree_le',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
