"""add structure deschamps 

Revision ID: 612f0eb1173c
Revises: 6e57bc7d0289
Create Date: 2026-08-22 07:04:14.030065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '612f0eb1173c'
down_revision: Union[str, Sequence[str], None] = '6e57bc7d0289'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('structures', sa.Column('cree_par_uid', sa.Uuid(), nullable=True))
    op.add_column('structures', sa.Column('modifie_par_uid', sa.Uuid(), nullable=True))
    op.add_column('structures', sa.Column('supprime_par_uid', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_structures_cree_par_uid'), 'structures', ['cree_par_uid'], unique=False)
    op.create_index(op.f('ix_structures_modifie_par_uid'), 'structures', ['modifie_par_uid'], unique=False)
    op.create_index(op.f('ix_structures_supprime_par_uid'), 'structures', ['supprime_par_uid'], unique=False)
    op.create_foreign_key(None, 'structures', 'users', ['supprime_par_uid'], ['uid'])
    op.create_foreign_key(None, 'structures', 'users', ['cree_par_uid'], ['uid'])
    op.create_foreign_key(None, 'structures', 'users', ['modifie_par_uid'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'structures', type_='foreignkey')
    op.drop_constraint(None, 'structures', type_='foreignkey')
    op.drop_constraint(None, 'structures', type_='foreignkey')
    op.drop_index(op.f('ix_structures_supprime_par_uid'), table_name='structures')
    op.drop_index(op.f('ix_structures_modifie_par_uid'), table_name='structures')
    op.drop_index(op.f('ix_structures_cree_par_uid'), table_name='structures')
    op.drop_column('structures', 'supprime_par_uid')
    op.drop_column('structures', 'modifie_par_uid')
    op.drop_column('structures', 'cree_par_uid')
    # ### end Alembic commands ###
