"""add eleve structures fields

Revision ID: 67ce8990e428
Revises: 39e78e0b0173
Create Date: 2026-08-21 05:20:27.079963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67ce8990e428'
down_revision: Union[str, Sequence[str], None] = '39e78e0b0173'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eleves', sa.Column('structure_uid', sa.Uuid(), nullable=True))
    op.drop_constraint(op.f('eleves_promotion_uid_fkey'), 'eleves', type_='foreignkey')
    op.drop_constraint(op.f('eleves_filieres_uid_fkey'), 'eleves', type_='foreignkey')
    op.drop_constraint(op.f('eleves_etablissement_uid_fkey'), 'eleves', type_='foreignkey')
    op.drop_constraint(op.f('eleves_nuveau_uid_fkey'), 'eleves', type_='foreignkey')
    op.create_foreign_key(None, 'eleves', 'structures', ['structure_uid'], ['uid'])
    op.drop_column('eleves', 'promotion_uid')
    op.drop_column('eleves', 'filieres_uid')
    op.drop_column('eleves', 'etablissement_uid')
    op.drop_column('eleves', 'nuveau_uid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eleves', sa.Column('nuveau_uid', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('eleves', sa.Column('etablissement_uid', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('eleves', sa.Column('filieres_uid', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('eleves', sa.Column('promotion_uid', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'eleves', type_='foreignkey')
    op.create_foreign_key(op.f('eleves_nuveau_uid_fkey'), 'eleves', 'niveaux', ['nuveau_uid'], ['uid'])
    op.create_foreign_key(op.f('eleves_etablissement_uid_fkey'), 'eleves', 'etablissements', ['etablissement_uid'], ['uid'])
    op.create_foreign_key(op.f('eleves_filieres_uid_fkey'), 'eleves', 'filieres', ['filieres_uid'], ['uid'])
    op.create_foreign_key(op.f('eleves_promotion_uid_fkey'), 'eleves', 'promotions', ['promotion_uid'], ['uid'])
    op.drop_column('eleves', 'structure_uid')
    # ### end Alembic commands ###
