"""add structure is_deleted fields

Revision ID: 6e57bc7d0289
Revises: ce08b9fc908d
Create Date: 2026-08-21 15:00:34.821991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e57bc7d0289'
down_revision: Union[str, Sequence[str], None] = 'ce08b9fc908d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('structures', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('structures', 'is_deleted')
    # ### end Alembic commands ###
