""" update table agent emploi_uid champ deleted

Revision ID: 6f04ee5cfec2
Revises: e7956b1ea752
Create Date: 2026-08-26 10:30:39.618154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f04ee5cfec2'
down_revision: Union[str, Sequence[str], None] = 'e7956b1ea752'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agents_emploi_uid'), table_name='agents')
    op.drop_constraint(op.f('agents_emploi_uid_fkey'), 'agents', type_='foreignkey')
    op.drop_column('agents', 'emploi_uid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('emploi_uid', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('agents_emploi_uid_fkey'), 'agents', 'emplois', ['emploi_uid'], ['uid'])
    op.create_index(op.f('ix_agents_emploi_uid'), 'agents', ['emploi_uid'], unique=False)
    # ### end Alembic commands ###
