""" update table classe_situation_administratives 

Revision ID: 8829de0bb5d2
Revises: e42893ae8c40
Create Date: 2026-08-27 08:22:26.973699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8829de0bb5d2'
down_revision: Union[str, Sequence[str], None] = 'e42893ae8c40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('situation_administratives_classe_situation_administrative__fkey'), 'situation_administratives', type_='foreignkey')
    op.create_foreign_key(None, 'situation_administratives', 'classe_situation_administratives', ['classe_situation_administrative_uid'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'situation_administratives', type_='foreignkey')
    op.create_foreign_key(op.f('situation_administratives_classe_situation_administrative__fkey'), 'situation_administratives', 'emplois', ['classe_situation_administrative_uid'], ['uid'])
    # ### end Alembic commands ###
