"""update message table fields date

Revision ID: 93ae3df1313a
Revises: a0c83ec76cca
Create Date: 2026-09-04 13:24:54.508310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93ae3df1313a'
down_revision: Union[str, Sequence[str], None] = 'a0c83ec76cca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('cree_le', sa.DateTime(), nullable=False))
    op.add_column('messages', sa.Column('modifie_le', sa.DateTime(), nullable=False))
    op.alter_column('messages', 'supprime_le',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('messages', 'archive_le',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('messages', 'lu_le',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('messages', 'livre_le')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('livre_le', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('messages', 'lu_le',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('messages', 'archive_le',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('messages', 'supprime_le',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('messages', 'modifie_le')
    op.drop_column('messages', 'cree_le')
    # ### end Alembic commands ###
