"""update categorie_uid in grades

Revision ID: 96e10e518dbd
Revises: 7c49e15262ff
Create Date: 2026-08-18 14:22:37.167483

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96e10e518dbd'
down_revision: Union[str, Sequence[str], None] = '7c49e15262ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_mode', sa.Boolean(), nullable=True),
    sa.Column('supprime_le', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('type_agents',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cree_par', sa.Uuid(), nullable=True),
    sa.Column('modifie_par', sa.Uuid(), nullable=True),
    sa.Column('supprime_par', sa.Uuid(), nullable=True),
    sa.Column('is_mode', sa.Boolean(), nullable=True),
    sa.Column('supprime_le', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cree_par'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['modifie_par'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['supprime_par'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_type_agents_cree_par'), 'type_agents', ['cree_par'], unique=False)
    op.create_index(op.f('ix_type_agents_modifie_par'), 'type_agents', ['modifie_par'], unique=False)
    op.create_index(op.f('ix_type_agents_supprime_par'), 'type_agents', ['supprime_par'], unique=False)
    op.add_column('grades', sa.Column('categorie_uid', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_grades_categorie_uid'), 'grades', ['categorie_uid'], unique=False)
    op.create_foreign_key(None, 'grades', 'categories', ['categorie_uid'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'grades', type_='foreignkey')
    op.drop_index(op.f('ix_grades_categorie_uid'), table_name='grades')
    op.drop_column('grades', 'categorie_uid')
    op.drop_index(op.f('ix_type_agents_supprime_par'), table_name='type_agents')
    op.drop_index(op.f('ix_type_agents_modifie_par'), table_name='type_agents')
    op.drop_index(op.f('ix_type_agents_cree_par'), table_name='type_agents')
    op.drop_table('type_agents')
    op.drop_table('categories')
    # ### end Alembic commands ###
