""" update table agent des  champs supprimes 

Revision ID: ad39d0f5403f
Revises: 6f04ee5cfec2
Create Date: 2026-08-26 11:10:39.889092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad39d0f5403f'
down_revision: Union[str, Sequence[str], None] = '6f04ee5cfec2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agents_nature_acte_nomination_fonctionactuelle_uid'), table_name='agents')
    op.drop_constraint(op.f('agents_nature_acte_nomination_fonctionactuelle_uid_fkey'), 'agents', type_='foreignkey')
    op.drop_column('agents', 'nature_acte_nomination_fonctionactuelle_uid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('nature_acte_nomination_fonctionactuelle_uid', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('agents_nature_acte_nomination_fonctionactuelle_uid_fkey'), 'agents', 'nature_acte_nomination_fonctionactuelles', ['nature_acte_nomination_fonctionactuelle_uid'], ['uid'])
    op.create_index(op.f('ix_agents_nature_acte_nomination_fonctionactuelle_uid'), 'agents', ['nature_acte_nomination_fonctionactuelle_uid'], unique=False)
    # ### end Alembic commands ###
