"""upadet table Actualites 

Revision ID: af698847078f
Revises: 1f8e330e808b
Create Date: 2026-09-02 14:30:28.981244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af698847078f'
down_revision: Union[str, Sequence[str], None] = '1f8e330e808b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actualites', sa.Column('cree_par_uid', sa.Uuid(), nullable=True))
    op.add_column('actualites', sa.Column('modifie_par_uid', sa.Uuid(), nullable=True))
    op.add_column('actualites', sa.Column('supprime_par_uid', sa.Uuid(), nullable=True))
    op.drop_constraint(op.f('actualites_cree_par_fkey'), 'actualites', type_='foreignkey')
    op.drop_constraint(op.f('actualites_categorie_uid_fkey'), 'actualites', type_='foreignkey')
    op.drop_constraint(op.f('actualites_supprime_par_fkey'), 'actualites', type_='foreignkey')
    op.drop_constraint(op.f('actualites_modifie_par_fkey'), 'actualites', type_='foreignkey')
    op.create_foreign_key(None, 'actualites', 'users', ['modifie_par_uid'], ['uid'])
    op.create_foreign_key(None, 'actualites', 'users', ['cree_par_uid'], ['uid'])
    op.create_foreign_key(None, 'actualites', 'users', ['supprime_par_uid'], ['uid'])
    op.create_foreign_key(None, 'actualites', 'categorie_actualites', ['categorie_uid'], ['uid'])
    op.drop_column('actualites', 'supprime_par')
    op.drop_column('actualites', 'cree_par')
    op.drop_column('actualites', 'modifie_par')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actualites', sa.Column('modifie_par', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('actualites', sa.Column('cree_par', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('actualites', sa.Column('supprime_par', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'actualites', type_='foreignkey')
    op.drop_constraint(None, 'actualites', type_='foreignkey')
    op.drop_constraint(None, 'actualites', type_='foreignkey')
    op.drop_constraint(None, 'actualites', type_='foreignkey')
    op.create_foreign_key(op.f('actualites_modifie_par_fkey'), 'actualites', 'users', ['modifie_par'], ['uid'])
    op.create_foreign_key(op.f('actualites_supprime_par_fkey'), 'actualites', 'users', ['supprime_par'], ['uid'])
    op.create_foreign_key(op.f('actualites_categorie_uid_fkey'), 'actualites', 'categories', ['categorie_uid'], ['uid'])
    op.create_foreign_key(op.f('actualites_cree_par_fkey'), 'actualites', 'users', ['cree_par'], ['uid'])
    op.drop_column('actualites', 'supprime_par_uid')
    op.drop_column('actualites', 'modifie_par_uid')
    op.drop_column('actualites', 'cree_par_uid')
    # ### end Alembic commands ###
