"""add phototheque fichier_key fieldsclear

Revision ID: b37abcee37d2
Revises: c95195399a72
Create Date: 2026-09-03 11:28:03.398924

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b37abcee37d2'
down_revision: Union[str, Sequence[str], None] = 'c95195399a72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phototheques', sa.Column('fichier_key', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.drop_column('phototheques', 'image_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phototheques', sa.Column('image_key', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('phototheques', 'fichier_key')
    # ### end Alembic commands ###
