"""add phototheque cree_par_uid modifie_par_uid supprime_par_uid fields

Revision ID: b3947d36687a
Revises: b37abcee37d2
Create Date: 2026-09-03 12:50:42.535574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3947d36687a'
down_revision: Union[str, Sequence[str], None] = 'b37abcee37d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phototheques', sa.Column('cree_par_uid', sa.Uuid(), nullable=True))
    op.add_column('phototheques', sa.Column('modifie_par_uid', sa.Uuid(), nullable=True))
    op.add_column('phototheques', sa.Column('supprime_par_uid', sa.Uuid(), nullable=True))
    op.drop_constraint(op.f('phototheques_modifie_par_fkey'), 'phototheques', type_='foreignkey')
    op.drop_constraint(op.f('phototheques_cree_par_fkey'), 'phototheques', type_='foreignkey')
    op.drop_constraint(op.f('phototheques_supprime_par_fkey'), 'phototheques', type_='foreignkey')
    op.create_foreign_key(None, 'phototheques', 'users', ['supprime_par_uid'], ['uid'])
    op.create_foreign_key(None, 'phototheques', 'users', ['cree_par_uid'], ['uid'])
    op.create_foreign_key(None, 'phototheques', 'users', ['modifie_par_uid'], ['uid'])
    op.drop_column('phototheques', 'supprime_par')
    op.drop_column('phototheques', 'modifie_par')
    op.drop_column('phototheques', 'cree_par')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phototheques', sa.Column('cree_par', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('phototheques', sa.Column('modifie_par', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('phototheques', sa.Column('supprime_par', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'phototheques', type_='foreignkey')
    op.drop_constraint(None, 'phototheques', type_='foreignkey')
    op.drop_constraint(None, 'phototheques', type_='foreignkey')
    op.create_foreign_key(op.f('phototheques_supprime_par_fkey'), 'phototheques', 'users', ['supprime_par'], ['uid'])
    op.create_foreign_key(op.f('phototheques_cree_par_fkey'), 'phototheques', 'users', ['cree_par'], ['uid'])
    op.create_foreign_key(op.f('phototheques_modifie_par_fkey'), 'phototheques', 'users', ['modifie_par'], ['uid'])
    op.drop_column('phototheques', 'supprime_par_uid')
    op.drop_column('phototheques', 'modifie_par_uid')
    op.drop_column('phototheques', 'cree_par_uid')
    # ### end Alembic commands ###
