"""update BD 

Revision ID: b40ce523e4be
Revises: 4f7695183cbe
Create Date: 2026-08-19 08:17:09.694164

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b40ce523e4be'
down_revision: Union[str, Sequence[str], None] = '4f7695183cbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classe_situation_administratives',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_mode', sa.Boolean(), nullable=True),
    sa.Column('supprime_le', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('conjoints',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('prenoms', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('matricule_cnps', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('preofession', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_mode', sa.Boolean(), nullable=True),
    sa.Column('supprime_le', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('nature_acte_nomination_dans_emplois',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_mode', sa.Boolean(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('supprime_le', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('position_administratives',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_mode', sa.Boolean(), nullable=True),
    sa.Column('supprime_le', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('echelons',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cree_par', sa.Uuid(), nullable=True),
    sa.Column('modifie_par', sa.Uuid(), nullable=True),
    sa.Column('supprime_par', sa.Uuid(), nullable=True),
    sa.Column('is_mode', sa.Boolean(), nullable=True),
    sa.Column('supprime_le', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cree_par'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['modifie_par'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['supprime_par'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_echelons_cree_par'), 'echelons', ['cree_par'], unique=False)
    op.create_index(op.f('ix_echelons_modifie_par'), 'echelons', ['modifie_par'], unique=False)
    op.create_index(op.f('ix_echelons_supprime_par'), 'echelons', ['supprime_par'], unique=False)
    op.add_column('enseignants', sa.Column('nom_jeune_fille', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('enseignants', sa.Column('nom_prenoms_pere', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('enseignants', sa.Column('nom_prenoms_mere', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('enseignants', sa.Column('numero_piece_identite', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('enseignants', sa.Column('etat_handicap', sa.Boolean(), nullable=True))
    op.add_column('enseignants', sa.Column('nature_piece_identite_uid', sa.Uuid(), nullable=True))
    op.alter_column('enseignants', 'nombre_enfant',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_enseignants_nature_piece_identite_uid'), 'enseignants', ['nature_piece_identite_uid'], unique=False)
    op.drop_constraint(op.f('enseignants_genre_uid_fkey'), 'enseignants', type_='foreignkey')
    op.create_foreign_key(None, 'enseignants', 'genres', ['genre_uid'], ['uid'])
    op.create_foreign_key(None, 'enseignants', 'nature_pieceidentites', ['nature_piece_identite_uid'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'enseignants', type_='foreignkey')
    op.drop_constraint(None, 'enseignants', type_='foreignkey')
    op.create_foreign_key(op.f('enseignants_genre_uid_fkey'), 'enseignants', 'users', ['genre_uid'], ['uid'])
    op.drop_index(op.f('ix_enseignants_nature_piece_identite_uid'), table_name='enseignants')
    op.alter_column('enseignants', 'nombre_enfant',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('enseignants', 'nature_piece_identite_uid')
    op.drop_column('enseignants', 'etat_handicap')
    op.drop_column('enseignants', 'numero_piece_identite')
    op.drop_column('enseignants', 'nom_prenoms_mere')
    op.drop_column('enseignants', 'nom_prenoms_pere')
    op.drop_column('enseignants', 'nom_jeune_fille')
    op.drop_index(op.f('ix_echelons_supprime_par'), table_name='echelons')
    op.drop_index(op.f('ix_echelons_modifie_par'), table_name='echelons')
    op.drop_index(op.f('ix_echelons_cree_par'), table_name='echelons')
    op.drop_table('echelons')
    op.drop_table('position_administratives')
    op.drop_table('nature_acte_nomination_dans_emplois')
    op.drop_table('conjoints')
    op.drop_table('classe_situation_administratives')
    # ### end Alembic commands ###
