"""ajout document_justificati 

Revision ID: b9212bef5f95
Revises: 114393f76361
Create Date: 2026-08-18 20:21:59.018453

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9212bef5f95'
down_revision: Union[str, Sequence[str], None] = '114393f76361'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('type_document_justificatifs',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cree_par', sa.Uuid(), nullable=True),
    sa.Column('modifie_par', sa.Uuid(), nullable=True),
    sa.Column('supprime_par', sa.Uuid(), nullable=True),
    sa.Column('is_mode', sa.Boolean(), nullable=True),
    sa.Column('supprime_le', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cree_par'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['modifie_par'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['supprime_par'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_type_document_justificatifs_cree_par'), 'type_document_justificatifs', ['cree_par'], unique=False)
    op.create_index(op.f('ix_type_document_justificatifs_modifie_par'), 'type_document_justificatifs', ['modifie_par'], unique=False)
    op.create_index(op.f('ix_type_document_justificatifs_supprime_par'), 'type_document_justificatifs', ['supprime_par'], unique=False)
    op.create_table('document_justificatifs',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('taille', sa.Integer(), nullable=False),
    sa.Column('nom_fichier', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('extension', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cree_par', sa.Uuid(), nullable=True),
    sa.Column('modifie_par', sa.Uuid(), nullable=True),
    sa.Column('supprime_par', sa.Uuid(), nullable=True),
    sa.Column('is_mode', sa.Boolean(), nullable=True),
    sa.Column('supprime_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('type_document_justificatif_uid', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['cree_par'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['modifie_par'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['supprime_par'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['type_document_justificatif_uid'], ['type_document_justificatifs.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_document_justificatifs_cree_par'), 'document_justificatifs', ['cree_par'], unique=False)
    op.create_index(op.f('ix_document_justificatifs_modifie_par'), 'document_justificatifs', ['modifie_par'], unique=False)
    op.create_index(op.f('ix_document_justificatifs_supprime_par'), 'document_justificatifs', ['supprime_par'], unique=False)
    op.create_index(op.f('ix_document_justificatifs_type_document_justificatif_uid'), 'document_justificatifs', ['type_document_justificatif_uid'], unique=False)
    op.drop_index(op.f('ix_disciplines_cree_par'), table_name='disciplines')
    op.drop_index(op.f('ix_disciplines_modifie_par'), table_name='disciplines')
    op.drop_index(op.f('ix_disciplines_supprime_par'), table_name='disciplines')
    op.drop_constraint(op.f('disciplines_cree_par_fkey'), 'disciplines', type_='foreignkey')
    op.drop_constraint(op.f('disciplines_modifie_par_fkey'), 'disciplines', type_='foreignkey')
    op.drop_constraint(op.f('disciplines_supprime_par_fkey'), 'disciplines', type_='foreignkey')
    op.drop_column('disciplines', 'supprime_par')
    op.drop_column('disciplines', 'modifie_par')
    op.drop_column('disciplines', 'cree_par')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disciplines', sa.Column('cree_par', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('disciplines', sa.Column('modifie_par', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('disciplines', sa.Column('supprime_par', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('disciplines_supprime_par_fkey'), 'disciplines', 'users', ['supprime_par'], ['uid'])
    op.create_foreign_key(op.f('disciplines_modifie_par_fkey'), 'disciplines', 'users', ['modifie_par'], ['uid'])
    op.create_foreign_key(op.f('disciplines_cree_par_fkey'), 'disciplines', 'users', ['cree_par'], ['uid'])
    op.create_index(op.f('ix_disciplines_supprime_par'), 'disciplines', ['supprime_par'], unique=False)
    op.create_index(op.f('ix_disciplines_modifie_par'), 'disciplines', ['modifie_par'], unique=False)
    op.create_index(op.f('ix_disciplines_cree_par'), 'disciplines', ['cree_par'], unique=False)
    op.drop_index(op.f('ix_document_justificatifs_type_document_justificatif_uid'), table_name='document_justificatifs')
    op.drop_index(op.f('ix_document_justificatifs_supprime_par'), table_name='document_justificatifs')
    op.drop_index(op.f('ix_document_justificatifs_modifie_par'), table_name='document_justificatifs')
    op.drop_index(op.f('ix_document_justificatifs_cree_par'), table_name='document_justificatifs')
    op.drop_table('document_justificatifs')
    op.drop_index(op.f('ix_type_document_justificatifs_supprime_par'), table_name='type_document_justificatifs')
    op.drop_index(op.f('ix_type_document_justificatifs_modifie_par'), table_name='type_document_justificatifs')
    op.drop_index(op.f('ix_type_document_justificatifs_cree_par'), table_name='type_document_justificatifs')
    op.drop_table('type_document_justificatifs')
    # ### end Alembic commands ###
