"""add phototheque est_mis_en_avant fields

Revision ID: bd67b03d99fb
Revises: b3947d36687a
Create Date: 2026-09-03 13:06:39.531910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd67b03d99fb'
down_revision: Union[str, Sequence[str], None] = 'b3947d36687a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('phototheques', 'est_mis_en_avant',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('phototheques', 'ordre_affichage',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('phototheques', 'nombre_vues',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_phototheques_supprime_le'), 'phototheques', ['supprime_le'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_phototheques_supprime_le'), table_name='phototheques')
    op.alter_column('phototheques', 'nombre_vues',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('phototheques', 'ordre_affichage',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('phototheques', 'est_mis_en_avant',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
