"""ajout modifications

Revision ID: c2087dac9ec3
Revises: d24cc94bd6c1
Create Date: 2026-08-18 17:58:23.336201

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2087dac9ec3'
down_revision: Union[str, Sequence[str], None] = 'd24cc94bd6c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nature_pieceidentites',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_mode', sa.Boolean(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('supprime_le', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('pays',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_mode', sa.Boolean(), nullable=True),
    sa.Column('supprime_le', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('villes',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_mode', sa.Boolean(), nullable=True),
    sa.Column('supprime_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pays_par', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['pays_par'], ['villes.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_villes_pays_par'), 'villes', ['pays_par'], unique=False)
    op.drop_index(op.f('ix_type_emplois_cree_par'), table_name='type_emplois')
    op.drop_index(op.f('ix_type_emplois_modifie_par'), table_name='type_emplois')
    op.drop_index(op.f('ix_type_emplois_supprime_par'), table_name='type_emplois')
    op.drop_constraint(op.f('type_emplois_cree_par_fkey'), 'type_emplois', type_='foreignkey')
    op.drop_constraint(op.f('type_emplois_supprime_par_fkey'), 'type_emplois', type_='foreignkey')
    op.drop_constraint(op.f('type_emplois_modifie_par_fkey'), 'type_emplois', type_='foreignkey')
    op.drop_column('type_emplois', 'cree_par')
    op.drop_column('type_emplois', 'modifie_par')
    op.drop_column('type_emplois', 'supprime_par')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('type_emplois', sa.Column('supprime_par', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('type_emplois', sa.Column('modifie_par', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('type_emplois', sa.Column('cree_par', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('type_emplois_modifie_par_fkey'), 'type_emplois', 'users', ['modifie_par'], ['uid'])
    op.create_foreign_key(op.f('type_emplois_supprime_par_fkey'), 'type_emplois', 'users', ['supprime_par'], ['uid'])
    op.create_foreign_key(op.f('type_emplois_cree_par_fkey'), 'type_emplois', 'users', ['cree_par'], ['uid'])
    op.create_index(op.f('ix_type_emplois_supprime_par'), 'type_emplois', ['supprime_par'], unique=False)
    op.create_index(op.f('ix_type_emplois_modifie_par'), 'type_emplois', ['modifie_par'], unique=False)
    op.create_index(op.f('ix_type_emplois_cree_par'), 'type_emplois', ['cree_par'], unique=False)
    op.drop_index(op.f('ix_villes_pays_par'), table_name='villes')
    op.drop_table('villes')
    op.drop_table('pays')
    op.drop_table('nature_pieceidentites')
    # ### end Alembic commands ###
