"""add categorie_phototheque fields

Revision ID: c3bf9be6c25f
Revises: f910ae74c9a4
Create Date: 2026-09-02 09:00:06.296850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3bf9be6c25f'
down_revision: Union[str, Sequence[str], None] = 'f910ae74c9a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_categories_phototheques_slug'), table_name='categories_phototheques')
    op.drop_column('categories_phototheques', 'couleur')
    op.drop_column('categories_phototheques', 'description')
    op.drop_column('categories_phototheques', 'ordre_affichage')
    op.drop_column('categories_phototheques', 'slug')
    op.drop_column('categories_phototheques', 'icone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories_phototheques', sa.Column('icone', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('categories_phototheques', sa.Column('slug', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('categories_phototheques', sa.Column('ordre_affichage', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('categories_phototheques', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('categories_phototheques', sa.Column('couleur', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_categories_phototheques_slug'), 'categories_phototheques', ['slug'], unique=True)
    # ### end Alembic commands ###
