"""add phototheque image_key fields

Revision ID: c95195399a72
Revises: af698847078f
Create Date: 2026-09-03 11:06:17.780352

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c95195399a72'
down_revision: Union[str, Sequence[str], None] = 'af698847078f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phototheques', sa.Column('image_key', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('phototheques', 'image_key')
    # ### end Alembic commands ###
