"""add agent preinscrit_le et est_preinscrit fields

Revision ID: ce08b9fc908d
Revises: 67ce8990e428
Create Date: 2026-08-21 10:35:32.025196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce08b9fc908d'
down_revision: Union[str, Sequence[str], None] = '67ce8990e428'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('preinscrit_le', sa.DateTime(timezone=True), nullable=True))
    op.add_column('agents', sa.Column('est_preinscrit', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'est_preinscrit')
    op.drop_column('agents', 'preinscrit_le')
    # ### end Alembic commands ###
