"""update Communique fields code

Revision ID: ced690d2e31d
Revises: 52927702f50e
Create Date: 2026-09-02 09:50:35.137286

"""
from typing import Sequence, Union
import sqlmodel 
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ced690d2e31d'
down_revision: Union[str, Sequence[str], None] = '52927702f50e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('communiques', sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('communiques', 'code')
    # ### end Alembic commands ###
