""" update table agent 

Revision ID: d04c8290310c
Revises: 5fdff180d57c
Create Date: 2026-08-24 15:33:54.817292

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd04c8290310c'
down_revision: Union[str, Sequence[str], None] = '5fdff180d57c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('email_personnel', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.drop_column('agents', 'email_personneö')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('email_personneö', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('agents', 'email_personnel')
    # ### end Alembic commands ###
