"""update ClientPubKey session_uid fileds

Revision ID: d0ed71e09119
Revises: 6281a68aee13
Create Date: 2026-09-05 20:03:00.876368

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0ed71e09119'
down_revision: Union[str, Sequence[str], None] = '6281a68aee13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_public_keys',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('session_uid', sa.Uuid(), nullable=False),
    sa.Column('user_uid', sa.Uuid(), nullable=True),
    sa.Column('public_key', sa.Text(), nullable=False),
    sa.Column('algorithme', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('taille_cle', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_client_public_keys_is_active'), 'client_public_keys', ['is_active'], unique=False)
    op.create_index(op.f('ix_client_public_keys_session_uid'), 'client_public_keys', ['session_uid'], unique=True)
    op.create_index(op.f('ix_client_public_keys_uid'), 'client_public_keys', ['uid'], unique=False)
    op.create_index(op.f('ix_client_public_keys_user_uid'), 'client_public_keys', ['user_uid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_client_public_keys_user_uid'), table_name='client_public_keys')
    op.drop_index(op.f('ix_client_public_keys_uid'), table_name='client_public_keys')
    op.drop_index(op.f('ix_client_public_keys_session_uid'), table_name='client_public_keys')
    op.drop_index(op.f('ix_client_public_keys_is_active'), table_name='client_public_keys')
    op.drop_table('client_public_keys')
    # ### end Alembic commands ###
