"""add naturePieceidentiteclear

Revision ID: d24cc94bd6c1
Revises: 9fa2931ab9f7
Create Date: 2026-08-18 15:27:14.446637

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd24cc94bd6c1'
down_revision: Union[str, Sequence[str], None] = '9fa2931ab9f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
