""" update table conjoints 

Revision ID: e42893ae8c40
Revises: ad39d0f5403f
Create Date: 2026-08-26 12:09:52.781466

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e42893ae8c40'
down_revision: Union[str, Sequence[str], None] = 'ad39d0f5403f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conjoints', sa.Column('profession', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.drop_column('conjoints', 'preofession')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conjoints', sa.Column('preofession', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('conjoints', 'profession')
    # ### end Alembic commands ###
