""" update table agent nature_acte_nomination_fonctionactuelles champ

Revision ID: e7956b1ea752
Revises: d04c8290310c
Create Date: 2026-08-24 19:24:42.077506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7956b1ea752'
down_revision: Union[str, Sequence[str], None] = 'd04c8290310c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('nature_acte_nomination_fonctionactuelle_uid', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_agents_nature_acte_nomination_fonctionactuelle_uid'), 'agents', ['nature_acte_nomination_fonctionactuelle_uid'], unique=False)
    op.create_foreign_key(None, 'agents', 'nature_acte_nomination_fonctionactuelles', ['nature_acte_nomination_fonctionactuelle_uid'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agents', type_='foreignkey')
    op.drop_index(op.f('ix_agents_nature_acte_nomination_fonctionactuelle_uid'), table_name='agents')
    op.drop_column('agents', 'nature_acte_nomination_fonctionactuelle_uid')
    # ### end Alembic commands ###
