"""update Communique fields autres champs

Revision ID: ec581b0be72d
Revises: ced690d2e31d
Create Date: 2026-09-02 10:16:03.118176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec581b0be72d'
down_revision: Union[str, Sequence[str], None] = 'ced690d2e31d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('communiques', sa.Column('cree_par_uid', sa.Uuid(), nullable=True))
    op.add_column('communiques', sa.Column('modifie_par_uid', sa.Uuid(), nullable=True))
    op.add_column('communiques', sa.Column('supprime_par_uid', sa.Uuid(), nullable=True))
    op.drop_constraint(op.f('communiques_cree_par_fkey'), 'communiques', type_='foreignkey')
    op.drop_constraint(op.f('communiques_modifie_par_fkey'), 'communiques', type_='foreignkey')
    op.drop_constraint(op.f('communiques_supprime_par_fkey'), 'communiques', type_='foreignkey')
    op.create_foreign_key(None, 'communiques', 'users', ['supprime_par_uid'], ['uid'])
    op.create_foreign_key(None, 'communiques', 'users', ['cree_par_uid'], ['uid'])
    op.create_foreign_key(None, 'communiques', 'users', ['modifie_par_uid'], ['uid'])
    op.drop_column('communiques', 'modifie_par')
    op.drop_column('communiques', 'supprime_par')
    op.drop_column('communiques', 'cree_par')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('communiques', sa.Column('cree_par', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('communiques', sa.Column('supprime_par', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('communiques', sa.Column('modifie_par', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'communiques', type_='foreignkey')
    op.drop_constraint(None, 'communiques', type_='foreignkey')
    op.drop_constraint(None, 'communiques', type_='foreignkey')
    op.create_foreign_key(op.f('communiques_supprime_par_fkey'), 'communiques', 'users', ['supprime_par'], ['uid'])
    op.create_foreign_key(op.f('communiques_modifie_par_fkey'), 'communiques', 'users', ['modifie_par'], ['uid'])
    op.create_foreign_key(op.f('communiques_cree_par_fkey'), 'communiques', 'users', ['cree_par'], ['uid'])
    op.drop_column('communiques', 'supprime_par_uid')
    op.drop_column('communiques', 'modifie_par_uid')
    op.drop_column('communiques', 'cree_par_uid')
    # ### end Alembic commands ###
