"""add des tables

Revision ID: f910ae74c9a4
Revises: 8829de0bb5d2
Create Date: 2026-09-01 15:14:47.282577

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f910ae74c9a4'
down_revision: Union[str, Sequence[str], None] = '8829de0bb5d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorie_actualites',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_mode', sa.Boolean(), nullable=True),
    sa.Column('supprime_le', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('statut_messages',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_mode', sa.Boolean(), nullable=True),
    sa.Column('supprime_le', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('statut_services',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_mode', sa.Boolean(), nullable=True),
    sa.Column('supprime_le', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('type_information_contacts',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_mode', sa.Boolean(), nullable=True),
    sa.Column('supprime_le', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('type_messages',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_mode', sa.Boolean(), nullable=True),
    sa.Column('supprime_le', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('actualites',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('titre', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('resume', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('contenu', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('image_alt', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('auteur_uid', sa.Uuid(), nullable=True),
    sa.Column('categorie_uid', sa.Uuid(), nullable=True),
    sa.Column('statut', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('est_a_la_une', sa.Boolean(), nullable=False),
    sa.Column('nombre_vues', sa.Integer(), nullable=False),
    sa.Column('date_publication', sa.DateTime(), nullable=True),
    sa.Column('cree_le', sa.DateTime(), nullable=False),
    sa.Column('modifie_le', sa.DateTime(), nullable=False),
    sa.Column('cree_par', sa.Uuid(), nullable=True),
    sa.Column('modifie_par', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('supprime_le', sa.DateTime(), nullable=True),
    sa.Column('supprime_par', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['auteur_uid'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['categorie_uid'], ['categories.uid'], ),
    sa.ForeignKeyConstraint(['cree_par'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['modifie_par'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['supprime_par'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_actualites_auteur_uid'), 'actualites', ['auteur_uid'], unique=False)
    op.create_index(op.f('ix_actualites_categorie_uid'), 'actualites', ['categorie_uid'], unique=False)
    op.create_index(op.f('ix_actualites_date_publication'), 'actualites', ['date_publication'], unique=False)
    op.create_index(op.f('ix_actualites_est_a_la_une'), 'actualites', ['est_a_la_une'], unique=False)
    op.create_index(op.f('ix_actualites_is_deleted'), 'actualites', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_actualites_statut'), 'actualites', ['statut'], unique=False)
    op.create_table('categories_phototheques',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('icone', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('couleur', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('ordre_affichage', sa.Integer(), nullable=False),
    sa.Column('est_active', sa.Boolean(), nullable=False),
    sa.Column('cree_le', sa.DateTime(), nullable=False),
    sa.Column('modifie_le', sa.DateTime(), nullable=False),
    sa.Column('cree_par', sa.Uuid(), nullable=True),
    sa.Column('modifie_par', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('supprime_le', sa.DateTime(), nullable=True),
    sa.Column('supprime_par', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['cree_par'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['modifie_par'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['supprime_par'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_categories_phototheques_code'), 'categories_phototheques', ['code'], unique=True)
    op.create_index(op.f('ix_categories_phototheques_est_active'), 'categories_phototheques', ['est_active'], unique=False)
    op.create_index(op.f('ix_categories_phototheques_is_deleted'), 'categories_phototheques', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_categories_phototheques_libelle'), 'categories_phototheques', ['libelle'], unique=True)
    op.create_index(op.f('ix_categories_phototheques_slug'), 'categories_phototheques', ['slug'], unique=True)
    op.create_table('communiques',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('reference', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('titre', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('resume', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('contenu', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('fichier_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('statut', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('est_epingle', sa.Boolean(), nullable=False),
    sa.Column('date_publication', sa.DateTime(), nullable=True),
    sa.Column('date_expiration', sa.DateTime(), nullable=True),
    sa.Column('auteur_uid', sa.Uuid(), nullable=True),
    sa.Column('nombre_vues', sa.Integer(), nullable=False),
    sa.Column('nombre_telechargements', sa.Integer(), nullable=False),
    sa.Column('cree_le', sa.DateTime(), nullable=False),
    sa.Column('modifie_le', sa.DateTime(), nullable=False),
    sa.Column('cree_par', sa.Uuid(), nullable=True),
    sa.Column('modifie_par', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('supprime_le', sa.DateTime(), nullable=True),
    sa.Column('supprime_par', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['auteur_uid'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['cree_par'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['modifie_par'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['supprime_par'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_communiques_auteur_uid'), 'communiques', ['auteur_uid'], unique=False)
    op.create_index(op.f('ix_communiques_date_expiration'), 'communiques', ['date_expiration'], unique=False)
    op.create_index(op.f('ix_communiques_date_publication'), 'communiques', ['date_publication'], unique=False)
    op.create_index(op.f('ix_communiques_est_epingle'), 'communiques', ['est_epingle'], unique=False)
    op.create_index(op.f('ix_communiques_is_deleted'), 'communiques', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_communiques_reference'), 'communiques', ['reference'], unique=True)
    op.create_index(op.f('ix_communiques_statut'), 'communiques', ['statut'], unique=False)
    op.create_table('messages',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('objet', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('contenu', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expediteur_uid', sa.Uuid(), nullable=True),
    sa.Column('destinataire_uid', sa.Uuid(), nullable=False),
    sa.Column('est_important', sa.Boolean(), nullable=False),
    sa.Column('est_epingle', sa.Boolean(), nullable=False),
    sa.Column('est_lu', sa.Boolean(), nullable=False),
    sa.Column('envoye_le', sa.DateTime(), nullable=False),
    sa.Column('livre_le', sa.DateTime(), nullable=True),
    sa.Column('lu_le', sa.DateTime(), nullable=True),
    sa.Column('archive_le', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('supprime_le', sa.DateTime(), nullable=True),
    sa.Column('supprime_par', sa.Uuid(), nullable=True),
    sa.Column('type_message_uid', sa.Uuid(), nullable=True),
    sa.Column('statut_message_uid', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['destinataire_uid'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['expediteur_uid'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['statut_message_uid'], ['statut_messages.uid'], ),
    sa.ForeignKeyConstraint(['supprime_par'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['type_message_uid'], ['type_messages.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_messages_destinataire_uid'), 'messages', ['destinataire_uid'], unique=False)
    op.create_index(op.f('ix_messages_envoye_le'), 'messages', ['envoye_le'], unique=False)
    op.create_index(op.f('ix_messages_est_important'), 'messages', ['est_important'], unique=False)
    op.create_index(op.f('ix_messages_est_lu'), 'messages', ['est_lu'], unique=False)
    op.create_index(op.f('ix_messages_expediteur_uid'), 'messages', ['expediteur_uid'], unique=False)
    op.create_index(op.f('ix_messages_is_deleted'), 'messages', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_messages_statut_message_uid'), 'messages', ['statut_message_uid'], unique=False)
    op.create_index(op.f('ix_messages_type_message_uid'), 'messages', ['type_message_uid'], unique=False)
    op.create_table('phototheques',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('titre', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('image_couverture_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('lieu', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('date_evenement', sa.DateTime(), nullable=True),
    sa.Column('categorie_uid', sa.Uuid(), nullable=True),
    sa.Column('statut', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('est_mis_en_avant', sa.Boolean(), nullable=False),
    sa.Column('ordre_affichage', sa.Integer(), nullable=False),
    sa.Column('date_publication', sa.DateTime(), nullable=True),
    sa.Column('nombre_vues', sa.Integer(), nullable=False),
    sa.Column('cree_le', sa.DateTime(), nullable=False),
    sa.Column('modifie_le', sa.DateTime(), nullable=False),
    sa.Column('cree_par', sa.Uuid(), nullable=True),
    sa.Column('modifie_par', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('supprime_le', sa.DateTime(), nullable=True),
    sa.Column('supprime_par', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['categorie_uid'], ['categories_phototheques.uid'], ),
    sa.ForeignKeyConstraint(['cree_par'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['modifie_par'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['supprime_par'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_phototheques_categorie_uid'), 'phototheques', ['categorie_uid'], unique=False)
    op.create_index(op.f('ix_phototheques_date_evenement'), 'phototheques', ['date_evenement'], unique=False)
    op.create_index(op.f('ix_phototheques_date_publication'), 'phototheques', ['date_publication'], unique=False)
    op.create_index(op.f('ix_phototheques_est_mis_en_avant'), 'phototheques', ['est_mis_en_avant'], unique=False)
    op.create_index(op.f('ix_phototheques_is_deleted'), 'phototheques', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_phototheques_slug'), 'phototheques', ['slug'], unique=True)
    op.create_index(op.f('ix_phototheques_statut'), 'phototheques', ['statut'], unique=False)
    op.create_index(op.f('ix_phototheques_titre'), 'phototheques', ['titre'], unique=False)
    op.create_table('information_contacts',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('adresse', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('boite_postale', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('ville', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('pays', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('telephone_principal', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('telephone_secondaire', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('whatsapp', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('email_principal', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('email_secondaire', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('site_web', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('lien_google_maps', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('horaires_ouverture', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('facebook_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('linkedin_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('instagram_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('youtube_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('x_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('tiktok_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('structure_uid', sa.Uuid(), nullable=True),
    sa.Column('est_principal', sa.Boolean(), nullable=False),
    sa.Column('est_active', sa.Boolean(), nullable=False),
    sa.Column('ordre_affichage', sa.Integer(), nullable=False),
    sa.Column('cree_le', sa.DateTime(), nullable=False),
    sa.Column('modifie_le', sa.DateTime(), nullable=False),
    sa.Column('cree_par', sa.Uuid(), nullable=True),
    sa.Column('modifie_par', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('supprime_le', sa.DateTime(), nullable=True),
    sa.Column('supprime_par', sa.Uuid(), nullable=True),
    sa.Column('type_information_uid', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['cree_par'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['modifie_par'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['structure_uid'], ['structures.uid'], ),
    sa.ForeignKeyConstraint(['supprime_par'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['type_information_uid'], ['type_information_contacts.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_information_contacts_est_active'), 'information_contacts', ['est_active'], unique=False)
    op.create_index(op.f('ix_information_contacts_est_principal'), 'information_contacts', ['est_principal'], unique=False)
    op.create_index(op.f('ix_information_contacts_is_deleted'), 'information_contacts', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_information_contacts_libelle'), 'information_contacts', ['libelle'], unique=False)
    op.create_index(op.f('ix_information_contacts_structure_uid'), 'information_contacts', ['structure_uid'], unique=False)
    op.create_table('services',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description_courte', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('icone', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('conditions_acces', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pieces_requises', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('procedure', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('delai_traitement', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('cout', sa.Float(), nullable=True),
    sa.Column('lien_demande', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('telephone', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('adresse', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('horaires', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('structure_uid', sa.Uuid(), nullable=True),
    sa.Column('responsable_uid', sa.Uuid(), nullable=True),
    sa.Column('statut', sa.Enum('BROUILLON', 'PUBLIE', 'SUSPENDU', 'ARCHIVE', name='statutservice'), nullable=False),
    sa.Column('ordre_affichage', sa.Integer(), nullable=False),
    sa.Column('est_en_ligne', sa.Boolean(), nullable=False),
    sa.Column('est_mis_en_avant', sa.Boolean(), nullable=False),
    sa.Column('cree_le', sa.DateTime(), nullable=False),
    sa.Column('modifie_le', sa.DateTime(), nullable=False),
    sa.Column('statut_uid', sa.Uuid(), nullable=True),
    sa.Column('cree_par_uid', sa.Uuid(), nullable=True),
    sa.Column('modifie_par_uid', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('supprime_le', sa.DateTime(), nullable=True),
    sa.Column('supprime_par_uid', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['cree_par_uid'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['modifie_par_uid'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['responsable_uid'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['statut_uid'], ['statut_services.uid'], ),
    sa.ForeignKeyConstraint(['structure_uid'], ['structures.uid'], ),
    sa.ForeignKeyConstraint(['supprime_par_uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_services_code'), 'services', ['code'], unique=True)
    op.create_index(op.f('ix_services_est_en_ligne'), 'services', ['est_en_ligne'], unique=False)
    op.create_index(op.f('ix_services_est_mis_en_avant'), 'services', ['est_mis_en_avant'], unique=False)
    op.create_index(op.f('ix_services_is_deleted'), 'services', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_services_libelle'), 'services', ['libelle'], unique=False)
    op.create_index(op.f('ix_services_responsable_uid'), 'services', ['responsable_uid'], unique=False)
    op.create_index(op.f('ix_services_slug'), 'services', ['slug'], unique=True)
    op.create_index(op.f('ix_services_statut'), 'services', ['statut'], unique=False)
    op.create_index(op.f('ix_services_structure_uid'), 'services', ['structure_uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_services_structure_uid'), table_name='services')
    op.drop_index(op.f('ix_services_statut'), table_name='services')
    op.drop_index(op.f('ix_services_slug'), table_name='services')
    op.drop_index(op.f('ix_services_responsable_uid'), table_name='services')
    op.drop_index(op.f('ix_services_libelle'), table_name='services')
    op.drop_index(op.f('ix_services_is_deleted'), table_name='services')
    op.drop_index(op.f('ix_services_est_mis_en_avant'), table_name='services')
    op.drop_index(op.f('ix_services_est_en_ligne'), table_name='services')
    op.drop_index(op.f('ix_services_code'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_information_contacts_structure_uid'), table_name='information_contacts')
    op.drop_index(op.f('ix_information_contacts_libelle'), table_name='information_contacts')
    op.drop_index(op.f('ix_information_contacts_is_deleted'), table_name='information_contacts')
    op.drop_index(op.f('ix_information_contacts_est_principal'), table_name='information_contacts')
    op.drop_index(op.f('ix_information_contacts_est_active'), table_name='information_contacts')
    op.drop_table('information_contacts')
    op.drop_index(op.f('ix_phototheques_titre'), table_name='phototheques')
    op.drop_index(op.f('ix_phototheques_statut'), table_name='phototheques')
    op.drop_index(op.f('ix_phototheques_slug'), table_name='phototheques')
    op.drop_index(op.f('ix_phototheques_is_deleted'), table_name='phototheques')
    op.drop_index(op.f('ix_phototheques_est_mis_en_avant'), table_name='phototheques')
    op.drop_index(op.f('ix_phototheques_date_publication'), table_name='phototheques')
    op.drop_index(op.f('ix_phototheques_date_evenement'), table_name='phototheques')
    op.drop_index(op.f('ix_phototheques_categorie_uid'), table_name='phototheques')
    op.drop_table('phototheques')
    op.drop_index(op.f('ix_messages_type_message_uid'), table_name='messages')
    op.drop_index(op.f('ix_messages_statut_message_uid'), table_name='messages')
    op.drop_index(op.f('ix_messages_is_deleted'), table_name='messages')
    op.drop_index(op.f('ix_messages_expediteur_uid'), table_name='messages')
    op.drop_index(op.f('ix_messages_est_lu'), table_name='messages')
    op.drop_index(op.f('ix_messages_est_important'), table_name='messages')
    op.drop_index(op.f('ix_messages_envoye_le'), table_name='messages')
    op.drop_index(op.f('ix_messages_destinataire_uid'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_communiques_statut'), table_name='communiques')
    op.drop_index(op.f('ix_communiques_reference'), table_name='communiques')
    op.drop_index(op.f('ix_communiques_is_deleted'), table_name='communiques')
    op.drop_index(op.f('ix_communiques_est_epingle'), table_name='communiques')
    op.drop_index(op.f('ix_communiques_date_publication'), table_name='communiques')
    op.drop_index(op.f('ix_communiques_date_expiration'), table_name='communiques')
    op.drop_index(op.f('ix_communiques_auteur_uid'), table_name='communiques')
    op.drop_table('communiques')
    op.drop_index(op.f('ix_categories_phototheques_slug'), table_name='categories_phototheques')
    op.drop_index(op.f('ix_categories_phototheques_libelle'), table_name='categories_phototheques')
    op.drop_index(op.f('ix_categories_phototheques_is_deleted'), table_name='categories_phototheques')
    op.drop_index(op.f('ix_categories_phototheques_est_active'), table_name='categories_phototheques')
    op.drop_index(op.f('ix_categories_phototheques_code'), table_name='categories_phototheques')
    op.drop_table('categories_phototheques')
    op.drop_index(op.f('ix_actualites_statut'), table_name='actualites')
    op.drop_index(op.f('ix_actualites_is_deleted'), table_name='actualites')
    op.drop_index(op.f('ix_actualites_est_a_la_une'), table_name='actualites')
    op.drop_index(op.f('ix_actualites_date_publication'), table_name='actualites')
    op.drop_index(op.f('ix_actualites_categorie_uid'), table_name='actualites')
    op.drop_index(op.f('ix_actualites_auteur_uid'), table_name='actualites')
    op.drop_table('actualites')
    op.drop_table('type_messages')
    op.drop_table('type_information_contacts')
    op.drop_table('statut_services')
    op.drop_table('statut_messages')
    op.drop_table('categorie_actualites')
    # ### end Alembic commands ###
