"""update Visiteur_session fileds

Revision ID: fb271977b3b9
Revises: 3b525ff6966e
Create Date: 2026-09-06 12:38:15.565808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb271977b3b9'
down_revision: Union[str, Sequence[str], None] = '3b525ff6966e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visiteur_sessions',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('session_uid', sa.Uuid(), nullable=False),
    sa.Column('adresse_ip', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('derniere_activite_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expire_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('est_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_visiteur_sessions_adresse_ip'), 'visiteur_sessions', ['adresse_ip'], unique=False)
    op.create_index(op.f('ix_visiteur_sessions_derniere_activite_le'), 'visiteur_sessions', ['derniere_activite_le'], unique=False)
    op.create_index(op.f('ix_visiteur_sessions_est_active'), 'visiteur_sessions', ['est_active'], unique=False)
    op.create_index(op.f('ix_visiteur_sessions_expire_le'), 'visiteur_sessions', ['expire_le'], unique=False)
    op.create_index(op.f('ix_visiteur_sessions_session_uid'), 'visiteur_sessions', ['session_uid'], unique=True)
    op.create_index(op.f('ix_visiteur_sessions_uid'), 'visiteur_sessions', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visiteur_sessions_uid'), table_name='visiteur_sessions')
    op.drop_index(op.f('ix_visiteur_sessions_session_uid'), table_name='visiteur_sessions')
    op.drop_index(op.f('ix_visiteur_sessions_expire_le'), table_name='visiteur_sessions')
    op.drop_index(op.f('ix_visiteur_sessions_est_active'), table_name='visiteur_sessions')
    op.drop_index(op.f('ix_visiteur_sessions_derniere_activite_le'), table_name='visiteur_sessions')
    op.drop_index(op.f('ix_visiteur_sessions_adresse_ip'), table_name='visiteur_sessions')
    op.drop_table('visiteur_sessions')
    # ### end Alembic commands ###
